<?php
/**
 * Copyright ©FedEx, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="bulk-edit-warning-modal-container" id="bulk_edit_warning_modal_container" data-mage-init='{"bulkEditWarningModal": {}}' style="display: none;">
    <div class="bulk-edit-warning-modal-desrciption">
        <div class="bulk-edit-warning-modal-image">
            <img src="<?=$this->getViewFileUrl('images/user-group/BulkEditWarning-icon.png');?>" alt="Warning Icon">
        </div>
        <p>One or more of these users is currently assigned<span>to a user group.</span></p>
        <span>Would you like to change them to this user group?</span>
    </div>
    <div class="bulk-edit-warning-modal-buttons">
        <button class="bulk-edit-warning-modal-cancel-button" id="bulk_edit_warning_modal_cancel_button" type="button"><span>NO, CANCEL</span></button>
        <button class="bulk-edit-warning-modal-update-button" id="bulk_edit_warning_modal_update_button" type="button"><span>YES, CHANGE</span></button>
    </div>
</div>
