<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile
?>
<?php
$helperImageClass = '\Magento\Cms\Helper\Wysiwyg\Images';
if ($this->helper('\Fedex\Commercial\Helper\CommercialHelper')->isSelfRegAdminUpdates() == true) {
    $divClass = "search-filter";
    if ($this->helper('\Fedex\SDE\Helper\SdeHelper')->getIsSdeStore() == true) {
        $divClass = "search-filter-sde";
    }
    ?>
    <div class="field <?php echo $divClass;?> filters-collapse">
        <button id="filter-show-btn" class="action secondary" type="button">
            <div class="user-filter-image"></div>
            <div class="user-filter-image-text"><?=$escaper->escapeHtml(__('Filter')); ?></div>
        </button>
        <div class="user-filter-options">
            <div class="user-filter-main-div">
                <div class="user-filter-heading">
                    <span class="user-filter-heading-text"><?=$escaper->escapeHtml(__('Status')); ?></span>
                </div>
                <ul class="user-filter-list">
                    <li class="user-filter-status-options">
                        <input type="checkbox" name="user-filter-status" aria-label="Active" class="user-filter-status-checkbox" id="user-filter-status-checkbox" value="1" />
                        <span class="user-filter-heading-text"><?=$escaper->escapeHtml(__('Active')); ?></span>
                    </li>
                    <li class="user-filter-status-options">
                        <input type="checkbox" name="user-filter-status" aria-label="Inactive" class="user-filter-status-checkbox" id="user-filter-status-checkbox" value="0" />
                            <span class="user-filter-heading-text"><?=$escaper->escapeHtml(__('Inactive')); ?></span>
                    </li>
                    <li class="user-filter-status-options">
                        <input type="checkbox" name="user-filter-status" aria-label="Pending Approval" class="user-filter-status-checkbox" id="user-filter-status-checkbox" value="2" />
                            <span class="user-filter-heading-text"><?=$escaper->escapeHtml(__('Pending Approval')); ?></span>
                    </li>
                </ul>
                <button class="btn-primary user-filter-save-button" type="button"><?=$escaper->escapeHtml(__('Save')); ?></button>
            </div>
        </div>
    </div>
    <script>
    require(['jquery', 'reloadGrid'
    ],function($,reloadGrid,errorProcessor){
        $(document).ready(function() {
            $('#filter-show-btn').on('click', function(e) {
                var dim = $('.user-filter-options').is(":visible");
                if (dim == true) {
                    $('.user-filter-options').hide();
                }else{
                    $('.user-filter-options').show();
                }
                e.stopPropagation();
            });
            $('.user-filter-save-button').on('click', function(e) {
                var statusArray = [];
                $("input:checkbox[name=user-filter-status]:checked").each(function(){
                    statusArray.push($(this).val());
                });
                if (typeof statusArray !== 'undefined' && statusArray.length > 0) {
                    separator = ',';
                    statusfilterstr = statusArray.join(separator);
                    reloadGrid.reloadFilterUIComponent("company_users_listing.company_users_listing_data_source",statusfilterstr);
                }else {
                    statusfilterstr = "";
                    reloadGrid.reloadFilterUIComponent("company_users_listing.company_users_listing_data_source",statusfilterstr);
                }
                $(".user-filter-options").hide();
            });
            $('body').click(function() {
                $(".user-filter-options").hide();
            });
            $('.user-filter-options').click(function(e) {
                e.stopPropagation();
            });
            
        });
    });
    </script>
<?php } ?>