<div class="footer-container">
    <div class="footer">
        <?= $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('commercial_footer')
            ->toHtml();
        ?>
    </div>
</div>
<script type="text/javascript">
    require(['jquery','domReady!'], function($){
        if($('body').hasClass('selfreg-landing-index') || $('body').hasClass('selfreg-login-fail') || $('body').hasClass('oauth-fail-index')){
            $("figure.commercial-footer-img").attr("role","contentinfo");
        }
    });
</script>
