<header class="page-header wlgn-enable-page-header remove-role" style="margin-top:20px;border-bottom:1px solid #dce2e6">
    <div class="header content">
        <div id="toggle-menu">
            <span data-action="toggle-nav" class="action nav-toggle"><span>Toggle Nav</span></span>
        </div>
        <a class="logo" href="<?= $block->getBaseUrl()?>" title="<?= $block->getLogoAlt()?>" aria-label="store logo">
            <img src="<?= $block->getLogoSrc()?>" title="<?= $block->getLogoAlt()?>"
            alt="<?= $block->getLogoAlt()?>" width="170">
        </a>
    </div>
</header>
<div class="modal-inner-wrap" data-role="focusable-scope">
    <div id="modal-content-7" class="modal-content" data-role="content">
        <div id="login-register-popup" class="pod-upload-warning login-top-popup" style="">
            <div class="modal-body-content">
                <h1 class="note-heading"><?= $block->getTitle()?></h1>
                <p class="note-description">
                    <?= $block->getDescription();?>
                </p>
                <div class="row-1">
                    <div class="btn-container-left">
                        <a href="<?= $block->getRegistrationUrl()?>" class="btn-popup-create-user">
                            <span class="span-popup-create-user"><?= $block->getRegistrationBtnLabel();?>
                                <span></span>
                            </span>
                        </a>
                    </div>
                    <div class="btn-container-right">
                        <a href="<?= $block->getLoginUrl()?>" class="btn-popup-login">
                            <span class="span-popup-login"><?= $block->getLoginBtnLabel();?></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
