<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 */

$viewModelHelper = $block->getViewModelMvphelper();
?>
<p class="toolbar-amount" aria-label="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1):?>
        <?php if ($viewModelHelper->isCommercialCustomer()) {?>
            <?= $block->escapeHtml(
                   __(
                   '<span class="mobile-hide-items">Items</span> %1<span class="mobile-hide-dash">-</span><span class="mobile-hide-to">to</span>%2 of %3 <span class="mobile-hide-totals">total</span>',
                   '<span class="toolbar-number">' . $localeFormatter->formatNumber($block->getFirstNum()) . '</span>',
                   '<span class="toolbar-number">' . $localeFormatter->formatNumber($block->getLastNum()) . '</span>',
                   '<span class="toolbar-number bbb">' . $localeFormatter->formatNumber($block->getTotalNum()) . '</span>'
                   ),
                ['span']
            ) ?>
        <?php } else {?>
            <?= $block->escapeHtml(
                __(
                    'Items %1 to %2 of %3',
                    '<span class="toolbar-number">' . $localeFormatter->formatNumber($block->getFirstNum()) . '</span>',
                    '<span class="toolbar-number">' . $localeFormatter->formatNumber($block->getLastNum()) . '</span>',
                    '<span class="toolbar-number bbb">' . $localeFormatter->formatNumber($block->getTotalNum()) . '</span>'
                ),
                ['span']
            ) ?>
        <?php } elseif ($block->getTotalNum() == 1): ?>
        <?= $block->escapeHtml(
            __(
                '%1 Item',
                '<span class="toolbar-number">' . $localeFormatter->formatNumber($block->getTotalNum()) . '</span>'
            ),
            ['span']
        ) ?>
    <?php else:?>
        <?= $block->escapeHtml(
            __(
                '%1 Items',
                '<span class="toolbar-number">' . $localeFormatter->formatNumber($block->getTotalNum()) . '</span>'
            ),
            ['span']
        ) ?>
    <?php endif; ?>
</p>
