<?php
/**@var Fedex\SSO\ViewModel\SessionTimeout $sessionConfig */
/** @var \Magento\Framework\Escaper $escaper */
$sessionConfig = $block->getData('session_config');
$isEpro = $sessionConfig->getIsEproUser();
?>
<div id="fcl-session-modal" class="d-none">
    <div class="modal-contents mx-auto">
        <div class="cl-stone-gray text-center">
            <img class="img-title" alt="Session time icon"
                 src="<?php echo $block->getViewFileUrl('images/sso/icon_time.svg'); ?>">
            <h3 class="txt-title mt-0 weight-300">
                <span class="alert-content alert-title">
                    <?= $escaper->escapeHtml($sessionConfig->getSessionWarningPMessage()) ?>
                </span>
                <span class="expired-content expired-title">
                    <?= $escaper->escapeHtml($sessionConfig->getSessionExpiredPMessage()) ?>
                </span>
            </h3>
            <h3 class="fs-16 fedex-light lh-24 mt-0 mb-20 weight-300">
                <span class="alert-content alert-msg">
                    <?= $escaper->escapeHtml($sessionConfig->getSessionWarningSMessage()) ?>
                </span>
                <span class="expired-content expired-msg">
                    <?= $escaper->escapeHtml($sessionConfig->getSessionExpiredSMessage()) ?>
                </span>
            </h3>
            <h3 class="alert-content timer fedex-light lh-56 weight-300">
            </h3>
        </div>
        <div class="btn-group-actions d-flex h-center">
            <button data-role="closeBtn" class="alert-content btn-actions btn-action-primary">CONTINUE</button>
            <button class="alert-content btn-actions btn-action-secondary btn-home">RETURN HOME</button>
            <button data-role="closeBtn" class="expired-content btn-actions btn-action-primary btn-okay">OKAY</button>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Fedex_SSO/js/session_timeout_modal": {
                "session_warning_time": "<?= $sessionConfig->getSessionWarningTime() ?>",
                "profile_logout_time": "<?= $sessionConfig->getWebConfig() ?>",
                "isEproUser": "<?= $sessionConfig->getIsEproUser() ?>",
                "isEpro": "<?= $isEpro ?>",
                "loggedAsCustomerCustomerId": "<?= $sessionConfig->getAdminId() ?>",
                "mazegeeksCtcAdminImpersonator": "<?= $sessionConfig->getImpersonatorToggle() ?>"
            }
        }
    }
</script>
