<?php
/**
 * Copyright © FedEx, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var Fedex\OrderApprovalB2b\ViewModel\OrderApprovalViewModel $orderApprovalB2bViewModel */
$orderApprovalB2bViewModel = $block->getData('orderApprovalViewModal');
?>
<?php
if ($orderApprovalB2bViewModel->isOrderApprovalB2bEnabled()): ?>
    <div id="order-approve-modal-popup" class="orderb2b-approve-modal-popup-content" style="display:none">
        <div class="approve-warning-icon-container">
            <img class="approve-warning-icon" alt="Approve Warning"
            src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/commercial-order-approval/warning.png'));?>"/>
        </div>
        <h3 class="approve-title">
            <?= $escaper->escapeHtml(__('Are you sure you want to approve this order?')) ?>
        </h3>
        <div class="approve-message">
            <?= $escaper->escapeHtml(__('Upon approval, this order will begin processing.')) ?>
        </div>
        <div class="approve-popup-btn-container">
            <button type="button" class="btn-approve-cancel">
                <?= $escaper->escapeHtml(__('Cancel')) ?>
            </button>
            <button type="button" class="btn-approve-order">
                <?= $escaper->escapeHtml(__('Yes, Approve Order')) ?>
            </button>
        </div>
    </div>
    <script>
        require(['approveModalPopup'], function(approveModalPopup) {
        });
    </script>
<?php endif; ?>
