<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\NegotiableQuote\Block\Quote\Info\Links */
$labelCloseQuote = 'Close quote';
?>
<div class="actions quote-view-links">
    <?php if ($block->isAllowedManage()): ?>
        <a href="#"
           data-post='<?=/* @noEscape */$block->getCloseParams()?>'
           title="<?=$block->escapeHtmlAttr(__($labelCloseQuote))?>"
           class="btn-close action close<?=/* @noEscape */$block->isCloseAvailable() ? '' : ' _disabled'?>"
           data-mobile-label="<?=$block->escapeHtmlAttr(__($labelCloseQuote))?>">
            <span><?=$block->escapeHtml(__($labelCloseQuote))?></span>
        </a>
        <a class="action delete<?=/* @noEscape */$block->isDeleteAvailable() ? '' : ' _disabled'?>" href="#"
           data-mage-init='{"Magento_NegotiableQuote/js/negotiable-quote": {"deleteLinkSelector": "#deleteLink"}}'
           role="delete-quote" data-quote="1"
            <?=/* @noEscape */$block->isDeleteAvailable() ? '' : 'tabindex="-1"'?>
           data-mobile-label="<?=$block->escapeHtmlAttr(__('Delete'))?>">
            <span><?=$block->escapeHtml(__('Delete'))?></span>
        </a>
        <a aria-label="Delete Link" href="#" id="deleteLink"
            <?=/* @noEscape */$block->isDeleteAvailable() ? '' : 'tabindex="-1"'?>
           data-post='<?=/* @noEscape */$block->getDeleteParams()?>' ></a>
    <?php endif;?>

   <?php $orderHistoryHelper = $this->helper(\Fedex\Orderhistory\Helper\Data::class);
if ($orderHistoryHelper->isEnhancementEnabeled()) {
    ?>
    <!-- B-1234552- Validate all new component follow ADA compliance Order/Quote History -->
    <a class=" epro_print epro_print_button"
       href="<?=$block->escapeUrl($block->getPrintUrl())?>"
       data-mobile-label="<?=$block->escapeHtmlAttr(__('PRINT QUOTE'))?>"
       target="_blank">
        <span class = "epro_print_text"><?=$block->escapeHtml(__('PRINT QUOTE'))?></span>
    </a>
    <?php } else { ?>
        <a class="action print"
            href="<?=$block->escapeUrl($block->getPrintUrl())?>"
            data-mobile-label="<?=$block->escapeHtmlAttr(__('Print'))?>"
            target="_blank">
            <span><?=$block->escapeHtml(__('Print'))?></span>
        </a>
    <?php } ?>
</div>
