<?php
declare(strict_types=1)
/**
 * @copyright Copyright (c) 2021 Fedex.
 * @author    Matheus Laureano <matheus.laureano.osv@fedex.com>
 */
 /**
 * @var \Magento\Search\Block\Term $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if (count($block->getTerms()) > 0): ?>
    <ul class="search-terms">
        <?php foreach ($block->getTerms() as $_term): ?>
            <li id="term-<?= /* @noEscape */ $_term->getId() ?>" class="item">
                <a href="<?= $block->escapeUrl($block->getSearchUrl($_term)) ?>">
                    <?= $block->escapeHtml($_term->getQueryText()) ?>
                </a>
            </li>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                "font-size:" . ($_term->getRatio()*70+100) . "%;",
                'li#term-' . $_term->getId()
            ) ?>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <div class="message notice">
        <div><?= $block->escapeHtml(__('There are no search terms available.')) ?></div>
    </div>
<?php endif; ?>
