<?php
declare(strict_types=1);

/** @var $block \Magento\Catalog\Block\Product\View */
/** @var \Magento\Framework\Escaper $escaper */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php
/** @var Fedex\ProductBundle\ViewModel\BundleProductHandler $bundleProductHandlerViewModel */
$bundleProductHandlerViewModel = $block->getData('bundleProductHandlerViewModel'); ?>
<?php if ($bundleProductHandlerViewModel->isTigerE468338ToggleEnabled() && $_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr($buttonTitle) ?>"
                        class="text-uppercase action primary tocart"
                        id="product-addtocart-button">
                    <span><?= $escaper->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

