<?php

/** @var $escaper \Magento\Framework\Escaper */
/** @var $block \Magento\Framework\View\Element\Template */

?>

<div class="bg-purple-10 p-8 pr-16 border-r-8 mb-24 w-max-cont d-flex v-center">
    <img class="img-auto valign-text-bottom ml-5 mr-5"
         src="<?= $block->getViewFileUrl('Fedex_ProductBundle::images/bundle-purple.svg'); ?>" alt="bundle icon">
    <span class="fs-16 fedex-medium lh-24">
            Product Bundle
    </span>
</div>
