stage:
  global:
    X_FRAME_CONFIGURATION: '*'
    SKIP_HTML_MINIFICATION: true
    SKIP_SCD: false
    SCD_STRATEGY: "compact"
  build:
    QUALITY_PATCHES:
      - MDVA-19640
      - ACSD-61845
      - ACSD-60816
      - ACP2E-3705
  deploy:
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: false
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: [
          'categoryConsumer',
          'productConsumer',
          'readyForPickupEmailQueue',
          'updateOrderInformation',
          'catalogCleanupConsumer',
          'reorderInstanceConsumer',
          'quoteItemOptionsTableConsumer',
          'salesOrderItemTableConsumer',
          'cleanQuoteItemInstanceConsumer',
          'cleanUpdateQuoteItemInstanceConsumer',
          'updateOrderItemInstanceConsumer',
          'mars.SendToMars',
          'catalogEnableStoreConsumer',
          'catalogMvpItemDisableConsumer',
          'catalogMvpItemEnableConsumer',
          'genericEmailQueue',
          'productPriceSyncConsumer',
          'sendFujitsuReceiptConfirmationEmail',
          'sendOrderEmailQueue',
          'retryShipmentCreation',
          'createInvoiceMarketplaceOnlyOrders',
          'sendDeliveryNotification',
          'miraklWebhookProcessor',
          'docRefExtandExpireConsumer',
          'docRefAddConsumer',
          'docRefDeleteConsumer',
          'sendOrderToMiraklQueue',
          'salesForceCustomerSubscribe',
          'bulkDeleteConsumer',
          'customerExportProcessor',
          'catalogMigration',
          'productImgRemove',
          'checkout_cart_product_add_after',
          'categoryAttributeUpdate',
          'createCompanyEntitiesConsumer',
          'fedex.marketplaceproduct.image',
          'fedexSaaSCommonAllowedCustomerGroupsConsumer'
        ]
    CACHE_CONFIGURATION:
      _merge: true
      default:
        backend_options:
          use_stale_cache: false
      stale_cache_enabled:
        backend_options:
          use_stale_cache: true
      type:
        default:
          frontend: "default"
        layout:
          frontend: "stale_cache_enabled"
        block_html:
          frontend: "stale_cache_enabled"
        reflection:
          frontend: "stale_cache_enabled"
        config_integration:
          frontend: "stale_cache_enabled"
        config_integration_api:
          frontend: "stale_cache_enabled"
        full_page:
          frontend: "stale_cache_enabled"
        translate:
          frontend: "stale_cache_enabled"
      allow_parallel_generation: true
      frontend:
        default:
          backend_options:
            compress_data: 4              # 0-9
            compress_tags: 4              # 0-9
            compress_threshold: 20480     # don't compress files smaller than this value
            compression_lib: 'gzip'       # snappy and lzf for performance, gzip for high compression (~69%)
      graphql:
        id_salt: '2urgTLhPAKcHJH70J6PWBtub1dxBDVVJ'
      indexer:
        batch_size:
          catalogpermissions_category_update: 12000
          catalogpermissions_category_delete: 16000
          catalogpermissions_product_update: 20000
          catalogpermissions_product_delete: 30000
    REDIS_BACKEND: "\\Magento\\Framework\\Cache\\Backend\\RemoteSynchronizedCache"
    DATABASE_CONFIGURATION:
      connection:
        default:
          driver_options:
            1001: 1 #!php/const:\PDO::MYSQL_ATTR_LOCAL_INFILE equals 1001
        indexer:
          driver_options:
            1001: 1 #!php/const:\PDO::MYSQL_ATTR_LOCAL_INFILE equals 1001
      _merge: true
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        port: 6372
        timeout: 5
        disable_locking: 1
        bot_first_lifetime: 60
        bot_lifetime: 7200
        max_lifetime: 2592000
        min_lifetime: 60

