<?php
/**
 * @var \Fedex\MarketplaceCheckout\Block\Order\Email\Items $block
 */
?>
<?php $shipmentItemFormatted = $block->getShipmentItemsFormatted() ?>
<?php $shipmentItem = $shipmentItemFormatted['1p']; ?>
<?php $shipmentItemChildCount = count(array_filter($shipmentItemFormatted['1p'], function($item) { return isset($item['is_child']) && !$item['is_child']; })); ?>
<?php $shipmentItem3p = $shipmentItemFormatted['3p']; ?>
<?php $totalItems = 0; ?>
<?php $totalDetails = $this->getTotalDetails(); ?>
<?php $isExpectedDeliveryDateEnabled = $block->isExpectedDeliveryDateEnabled(); ?>
<?php $isFreightShippingEnabled = $block->isFreightShippingEnabled(); ?>
<?php $isEssendantToggleEnabled = $block->isEssendantToggleEnabled(); ?>
<?php $isCBBToggleEnabled = $block->isCBBToggleEnabled(); ?>
<?php
$freightText = '';
if ($isFreightShippingEnabled) {
    $freightText = $block->getFreightShippingSurchargeText();
} ?>

    <?php if (count($shipmentItem) > 0): ?>
    <table class="email-items fedEx-office-items" style="border-collapse: collapse;" width="100%">
        <thead>
            <tr>
                <th class="item-info" style="font-size: 16px; font-weight: 700; line-height: 24px; padding-top:8px; padding-bottom:8px; background-color: #F2F2F2; vertical-align: middle">
                    <div class="container" style="display: flex; align-items: center;vertical-align: middle">
                        <?php
                        $firstIndex = array_keys($shipmentItem);
                        if (isset($shipmentItem[reset($firstIndex)]['shipping_label']) &&
                            isset($shipmentItem[reset($firstIndex)]['shipping_total'])): ?>
                            <img class="icon pickup" style="margin-right: 8px;" alt="Delivery Icon Icon" width="32px"
                                 height="32px"
                                 src="<?= $block->getViewFileUrl('Fedex_MarketplaceCheckout::images/icons/delivery-gray.png') ?>"/>
                        <?php else: ?>
                            <img class="icon pickup" style="margin-right: 8px;" alt="Pickup Icon" width="32px"
                                 height="32px"
                                 src="<?= $block->getViewFileUrl('Fedex_MarketplaceCheckout::images/icons/store-gray.png') ?>"/>
                        <?php endif; ?>
                        <span style="font-size: 16px;font-weight: 700">
                            <?= $block->escapeHtml(__('FedEx Office (%1 %2)', $shipmentItemChildCount, $shipmentItemChildCount > 1? 'items':'item')) ?>
                        </span>
                    </div>
                </th>
                <th class="item-qty" style="font-size: 16px; font-weight: 700; line-height: 24px; padding-top:8px; padding-bottom:8px; background-color: #F2F2F2; vertical-align: middle; text-align: right;">
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>
                <th class="item-price" style="font-size: 16px; font-weight: 700; line-height: 24px; padding-top:8px; padding-bottom:8px; padding-right:8px; background-color: #F2F2F2; vertical-align: middle; text-align: right">
                    <?= $block->escapeHtml(__('Price')) ?>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($shipmentItem as $item) : ?>
                <?php if(isset($item['is_child']) && $item['is_child']) {
                    $itemInfoStyle = 'font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 32px; border-top: none;';
                    $qtyInfoStyle = 'font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: none; text-align: right;';
                    $priceInfoStyle = 'font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: none; text-align: right;';
                } else {
                    $itemInfoStyle = 'font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc;';
                    $qtyInfoStyle = 'font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc; text-align: right;';
                    $priceInfoStyle = 'font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc; text-align: right;';
                }?>
                <tr class="<?= $item['is_child'] ? 'child-item' : 'item'; ?>">
                    <td class="item-info" style="<?= $itemInfoStyle ?>">
                        <p class="product-name" style="font-weight: normal; margin-top: 0; margin-bottom: 5px;"><?= $item['name']; ?></p>
                    </td>
                    <td class="item-qty" style="<?= $qtyInfoStyle ?>"><?= (int) $item['qty'] ?></td>
                    <td class="item-price" style="<?= $priceInfoStyle ?>">
                        <span class="price"><?= $block->formattedCurrencyValue($item['row_total']) ?></span>
                    </td>
                </tr>
            <?php if(isset($item['is_child']) && !$item['is_child']){$totalItems++;} endforeach; ?>
            <?php if (isset($item['shipping_label']) && isset($item['shipping_total'])): ?>
                <tr class="item">
                    <td class="item-info" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc;" colspan="2">
                        <p class="product-name" style="font-weight: normal; margin-top: 0; margin-bottom: 5px;">
                            <strong><?= __("Shipping Method:") ?></strong> <?= $this->formatShippingMethodName($item['shipping_label']); ?><sup>®</sup>
                        </p>
                    </td>
                    <td class="item-price" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc; text-align: right;">
                        <span class="price"><?= $block->formattedCurrencyValue($item['shipping_total']) ?></span>
                    </td>
                </tr>
                <?php if ($isExpectedDeliveryDateEnabled && isset($item['shipping_expected_delivery_date']) && $item['shipping_expected_delivery_date']): ?>
                    <tr class="item">
                        <td class="item-info" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc;" colspan="3">
                            <p class="product-name" style="font-weight: normal; margin-top: 0; margin-bottom: 5px;">
                                <strong><?= __("Expected Delivery:") ?></strong> <?= $item['shipping_expected_delivery_date']; ?>
                            </p>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endif; ?>
        </tbody>
        <?php if (count($shipmentItem3p) == 0): ?>
        <tfoot class="order-totals">
        <tr class="subtotal">
            <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 16px 10px 4px; text-align: right;border-top: 1px solid #ccc;"><?= __("Items (%1)", $totalItems) ?></th>
            <td data-th="Subtotal" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 16px 10px 4px; text-align: right;border-top: 1px solid #ccc;">
                <span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['sub_total']); ?></span></td>
        </tr>
        <?php if ($totalDetails['shipping'] > 0): ?>
            <tr class="subtotal">
                <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 16px 10px 4px; text-align: right;"><?= __("Shipping") ?></th>
                <td data-th="Subtotal" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">
                    <span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['shipping']); ?></span></td>
            </tr>
        <?php endif; ?>
        <tr class="discount">
            <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; background-color: #f2f2f2; font-size: 14px; font-weight: 700; line-height: 24px; padding: 8px 10px 8px; text-align: right;">Total Discount</th>
            <td data-th="Discount" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; background-color: #f2f2f2; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 8px; text-align: right;"><span class="price" style="white-space: nowrap; font-weight: 700">-<?= $block->formattedCurrencyValue($totalDetails['discount']); ?></span></td>
        </tr>
        <?php foreach($totalDetails['discounts'] as $discount): ?>
            <?php if ($discount['price'] > 0): ?>
            <tr class="discount">
                <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; background-color: #f2f2f2; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 8px; text-align: right;"><?= $discount['label'] ?></th>
                <td data-th="Shipping &amp; Handling" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; background-color: #f2f2f2; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 8px; text-align: right;"><span class="price" style="white-space: nowrap;">-<?= $block->formattedCurrencyValue($discount['price']); ?></span></td>
            </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        <tr class="tax">
            <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 4px; text-align: right;">Tax</th>
            <td data-th="Tax" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 4px; text-align: right;"><span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['tax']); ?></span></td>
        </tr>
        <tr class="grand_total<?php if ($totalDetails['shipping_estimate'] > 0):?>_no_hr<?php endif; ?>">
            <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">Total</th>
            <td data-th="Grand Total" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">
                <span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['total']); ?></span>
            </td>
        </tr>
        <?php if ($totalDetails['shipping_estimate'] > 0): ?>
            <tr class="shipping_estimate">
                <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">Estimated Shipping Charges</th>
                <td data-th="Subtotal" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">
                    <span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['shipping_estimate']); ?></span></td>
            </tr>
        <?php endif; ?>
        </tfoot>
        <?php endif; ?>

    </table>
    <?php endif; ?>
    <?php
        $length = count($shipmentItem3p);
        $counter = 0;
    ?>
    <?php foreach ($shipmentItem3p as $key => $items): ?>
        <?php $counter++; ?>
        <table class="email-items fedEx-office-items" width="100%" style="border-collapse: collapse;">
            <thead>
            <tr>
                <th class="item-info" style="font-size: 16px; font-weight: 700; line-height: 24px; padding-top:8px; padding-bottom:8px; background-color: #F2F2F2; vertical-align: middle">
                    <div class="container" style="display: flex; align-items: center">
                        <img class="icon pickup" style="margin-right: 8px;" alt="Pickup Icon" width="32px" height="32px" src="<?= $block->getViewFileUrl('Fedex_MarketplaceCheckout::images/icons/delivery-gray.png') ?>"/>
                        <span style="padding-top:5px;">
                            <?= $block->escapeHtml(__('%1 (%2 %3)', $key, count($shipmentItem3p[$key]), count($items) > 1? 'items':'item')) ?>
                        </span>
                    </div>
                </th>
                <th class="item-qty" style="font-size: 16px; font-weight: 700; line-height: 24px; padding-top:8px; padding-bottom:8px; background-color: #F2F2F2; vertical-align: middle; text-align: right;">
                    <?= count($shipmentItem) == 0 ? $block->escapeHtml(__('Qty')) : '' ?>
                </th>
                <th class="item-price" style="font-size: 16px; font-weight: 700; line-height: 24px; padding-top:8px; padding-bottom:8px; padding-right:8px; background-color: #F2F2F2; vertical-align: middle; text-align: right">
                    <?= count($shipmentItem) == 0 ? $block->escapeHtml(__('Price')) : '' ?>
                </th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($items as $item) : ?>
                <tr class="item">
                    <td class="item-info" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc;">
                        <p class="product-name" style="font-weight: normal; margin-top: 0; margin-bottom: 5px;"><?= $item['name']; ?></p>
                    </td>
                    <td class="item-qty" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc; text-align: right;"><?= (int) $item['qty'] ?></td>
                    <td class="item-price" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc; text-align: right;">
                        <span class="price"><?= $block->formattedCurrencyValue($item['row_total']) ?></span>
                    </td>
                </tr>
                <?php $totalItems++; endforeach; ?>
                <tr class="item">
                    <td class="item-info" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc;" colspan="2">
                        <p class="product-name" style="font-weight: normal; margin-top: 0; margin-bottom: 5px;">
                            <strong><?= __("Shipping Method:") ?></strong> <?= $this->formatShippingMethodName($item['mirakl_shipping_label']); ?><sup>®</sup>
                        </p>
                        <?php if ($isFreightShippingEnabled && isset($item['surcharge']) && $item['surcharge'] > 0):?>
                            <p style="margin: 16px 0 3px 24px"><?= $freightText ?> <strong><?= $block->formattedCurrencyValue($item['surcharge']) ?></strong></p>
                        <?php endif; ?>
                    </td>
                    <td class="item-price" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc; text-align: right;">
                        <?php if($isEssendantToggleEnabled || $isCBBToggleEnabled):?>
                            <?php if($item['mirakl_shipping_total']):?>
                            <span class="price"><?= $block->formattedCurrencyValue($item['mirakl_shipping_total']) ?></span>
                            <?php else:?>
                                <span style="font-weight: 700;color: #008a00;">FREE</span>
                            <?php endif; ?>
                        <?php else:?>
                            <span class="price"><?= $block->formattedCurrencyValue($item['mirakl_shipping_total']) ?></span>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php if (isset($item['mirakl_shipping_expected_delivery']) && $item['mirakl_shipping_expected_delivery']): ?>
                    <tr class="item">
                        <td class="item-info" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; line-height:24px; font-weight: 400; padding: 13px 10px; border-top: 1px solid #ccc;" colspan="3">
                            <p class="product-name" style="font-weight: normal; margin-top: 0; margin-bottom: 5px;">
                                <strong><?= __("Expected Delivery:") ?></strong> <?= $item['mirakl_shipping_expected_delivery']; ?>
                            </p>
                        </td>
                    </tr>
                <?php endif; ?>
            </tbody>

            <?php if($length == $counter): ?>
                <tfoot class="order-totals">
                    <tr class="subtotal">
                        <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 16px 10px 4px; text-align: right;border-top: 1px solid #ccc;"><?= __("Items (%1)", $totalItems) ?></th>
                        <td data-th="Subtotal" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top;  font-size: 14px; font-weight: 400; line-height: 24px; padding: 16px 10px 4px; text-align: right;border-top: 1px solid #ccc;">
                            <span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['sub_total']); ?></span></td>
                    </tr>
                    <?php if($isEssendantToggleEnabled):?>
                        <tr class="subtotal">
                            <th colspan="2" scope="row"
                                style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;"><?= __("Shipping") ?></th>
                            <td data-th="Subtotal" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">
                                <?php if ($totalDetails['shipping']): ?>
                                <span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['shipping']); ?></span>
                                <?php else: ?>
                                    <span style="font-weight: 700;color: #008a00;">FREE</span>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php else: ?>
                        <?php if ($totalDetails['shipping'] > 0): ?>
                            <tr class="subtotal">
                                <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;"><?= __("Shipping") ?></th>
                                <td data-th="Subtotal" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">
                                    <span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['shipping']); ?></span></td>
                            </tr>
                        <?php endif; ?>
                    <?php endif; ?>
                    <tr class="discount">
                        <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; background-color: #f2f2f2; font-size: 14px; font-weight: 700; line-height: 24px; padding: 8px 10px 8px; text-align: right;">Total Discount</th>
                        <td data-th="Discount" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; background-color: #f2f2f2; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 8px; text-align: right;"><span class="price" style="white-space: nowrap; font-weight: 700">-<?= $block->formattedCurrencyValue($totalDetails['discount']); ?></span></td>
                    </tr>
                    <?php foreach($totalDetails['discounts'] as $discount): ?>
                        <?php if ($discount['price'] > 0): ?>
                            <tr class="discount">
                                <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; background-color: #f2f2f2; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 8px; text-align: right;"><?= $discount['label'] ?></th>
                                <td data-th="Shipping &amp; Handling" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; background-color: #f2f2f2; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 8px; text-align: right;"><span class="price" style="white-space: nowrap;">-<?= $block->formattedCurrencyValue($discount['price']); ?></span></td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <tr class="tax">
                        <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 4px; text-align: right;">Tax</th>
                        <td data-th="Tax" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 8px 10px 4px; text-align: right;"><span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['tax']); ?></span></td>
                    </tr>
                    <tr class="grand_total<?php if ($totalDetails['shipping_estimate'] > 0):?>_no_hr<?php endif; ?>">
                        <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">Total</th>
                        <td data-th="Grand Total" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">
                            <span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['total']); ?></span>
                        </td>
                    </tr>
                    <?php if ($totalDetails['shipping_estimate'] > 0): ?>
                        <tr class="shipping_estimate">
                            <th colspan="2" scope="row" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">Estimated Shipping Charges</th>
                            <td data-th="Subtotal" style="font-family: &quot;Open Sans&quot;,&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif; vertical-align: top; font-size: 14px; font-weight: 400; line-height: 24px; padding: 4px 10px 8px; text-align: right;">
                                <span class="price" style="white-space: nowrap;"><?= $block->formattedCurrencyValue($totalDetails['shipping_estimate']); ?></span></td>
                        </tr>
                    <?php endif; ?>
                </tfoot>
            <?php endif; ?>
        </table>
    <?php endforeach; ?>

