<?php
/**
 * Fedex\SelfReg\Block\UserGroupsList $block
 */

$isAddEditFolderAccessEnabled = $block->getAddEditFolderAccess();

if ($isAddEditFolderAccessEnabled):
$data = json_encode(['editFolderAccess'=>[]]);
$jsonData = htmlspecialchars($data, ENT_QUOTES, 'UTF-8');

?>

<!-- Modal popup for Edit Folder Access -->
<div id="folder-permission-edit-folder-access-modal" class="folder-permission-edit-folder-access-modal" data-mage-init='<?php echo $jsonData; ?>' style="display:none;">
    <h2>Edit Folder Access</h2>
    <div class="folder-permission-edit-folder-access-modal-body"></div>
</div>
<?php endif; ?>
