<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\OrderHistorySearch\Block\Filters $block
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

$previousDate = date("m/d/Y", strtotime(' - 1 days'));
$datePlaceHolder = $previousDate." - ".date("m/d/Y");
$datePlaceHolderValue = '';
/** @var Fedex\Orderhistory\ViewModel\OrderHistoryEnhacement $viewModel */
$viewModel = $block->getData('order_enhancement_view_model');
$eproReorderToggleEnabled = $viewModel->isCommercialOrderHistoryReorderEnabled();
$isReorderEnabled = $viewModel->isReorderEnabled();
$recipientEmailAddressLimit = $viewModel->getRecipientEmailAddressLimit();
$helperImageClass = '\Magento\Cms\Helper\Wysiwyg\Images';

$historyurl =  $block->getBaseUrl().'sales/order/history/';
//Shared Order code start
$sharedEnhancementViewModel = $block->getData('shared_enhancement_view_model');
if ($sharedEnhancementViewModel->isSharedOrderPage()) {
    $historyurl =  $block->getBaseUrl().'shared/order/history/';
    $searchUrl = str_replace('sales/order/history', 'shared/order/history', $block->getSearchPostUrl());
} else {
    $searchUrl = $block->getSearchPostUrl();
}
//Shared Order code end

$isSharedOrderEnhancementToggle = $sharedEnhancementViewModel->isCustomerReportingEnhancementToggleEnabled();
$timeframeOptions = $sharedEnhancementViewModel->getTimeframeOptions();
$timeframeSelectOptions = $sharedEnhancementViewModel->getTimeframeSelectOptions();
$timeframeDownIcon = $block->getViewFileUrl('Fedex_SharedDetails::images/down.png');

$dateChoosen = $block->getRequest()->getParam('order-date');
if ($dateChoosen != "" && $dateChoosen != null) {
    $datePlaceHolderValue = $dateChoosen;
}

// B-1145903 - Show Order History with only shipped, ready for pickup or delivered
$orderStatus = $block->getRequest()->getParam('order-status');
$orderHistoryHelper =  $this->helper(Fedex\Orderhistory\Helper\Data::class);
// B-1213999 - "View Order" for completed should redirect to Order
//History with only shipped, ready for pickup, or complete
$isSDEHomepageEnable = $orderHistoryHelper->isSDEHomepageEnable();
$isEProHomepageEnable = $orderHistoryHelper->isEProHomepageEnable();
?>
<form data-mage-init='{"myOrdersFilter": {}, "validation": {}}'
    class="form search epro-my-orders-search-advanced my-orders-search-advanced
    <?= $eproReorderToggleEnabled ?
    $block->escapeHtmlAttr(__('epro-reorder-button')) : $block->escapeHtmlAttr(__(''));?>"
    action="<?=$escaper->escapeUrl($searchUrl); ?>"
    method="get"
    id="my-orders-search-advanced-form">
    <input type="hidden" id="advanced-filtering" name="advanced-filtering" value="" />
    <fieldset class="fieldset info">
        <div class="field search-sku retails-sku field-50"
             data-filter-label="<?=$escaper->escapeHtmlAttr(__('Product Name')); ?>">
            <div class="control">
                <input type="text" name="product-name-sku" id="product-name-sku"
                    value="<?=$escaper->escapeHtmlAttr($block->prepareInputValue('product-name-sku')); ?>"
                    minlength="<?=(int)$block->getMinInputLength(); ?>"
                    placeholder="<?=$escaper->escapeHtmlAttr(__('Search by Product Name')); ?>"
                     class="input-text order-filter-field"/>
                <button type="submit" aria-label="Search"></button>
            </div>
        </div>
        <?php if ($eproReorderToggleEnabled) { ?>
            <div class="field field-50 filters-collapse">
                <button id="filter-show-btn" class="action secondary" type="button">
                    <img src="<?=$this->helper($helperImageClass)->getBaseUrl().
                    'wysiwyg/filter.png';?>"
                        alt="filters" height="40" />
                    <?=$escaper->escapeHtml(__('Filter')); ?>
                </button>
                <?php if ($sharedEnhancementViewModel->isSharedOrderPage()) { ?>
                    <span data-bind="scope: 'export-commercial-reporting'">
                        <button id="export-commercial-reporting-btn" class="shared-order-btn"
                         data-bind="click: commercialReportingPopupModel" type="button">
                            <?= $escaper->escapeHtml(__('Export'));?>
                        </button>
                    </span>
                <?php } else { ?>
                        <?php if ($isReorderEnabled) { ?>
                            <span data-bind="scope: 'reorder_section'">
                                <button id="reorder-btn" class="action epro-reorder-btn"
                                data-bind="click: submitReorder" type="button" disabled="disabled">
                                    <?=$escaper->escapeHtml(__('REORDER')); ?>
                                </button>
                            </span>
                        <?php } ?>
                <?php } ?>
            </div>
        <?php } else { ?>
            <div class="field field-50 filters-collapse">
            <!-- B-1092709- Reset button on order view and Quote page -->
                <button id="filter-show-btn" class="action secondary" type="button">
                    <img src="<?=$this->helper($helperImageClass)->getBaseUrl().
                    'wysiwyg/filter.png';?>"
                        alt="filters" height="40" />
                    <?=$escaper->escapeHtml(__('Filter')); ?>
                </button>
                <!-- B-1234552- Validate all new component follow ADA compliance Order/Quote History -->
                <button id="filter-close-btn" class="action secondary filter-close" type="button">
                    <img src="<?=$this->helper($helperImageClass)->getBaseUrl().
                    'wysiwyg/close.png';?>"
                        alt="close-button" height="40" />
                    <?=$escaper->escapeHtml(__('Close')); ?>
                </button>
                <?php if ($sharedEnhancementViewModel->isSharedOrderPage()) { ?>
                <span data-bind="scope: 'export-commercial-reporting'">
                    <button id="export-commercial-reporting-btn" class="shared-order-btn"
                     data-bind="click: commercialReportingPopupModel" type="button">
                        <?= $escaper->escapeHtml(__('Export'));?>
                    </button>
                </span>
                <?php }?>
            </div>
        <?php } ?>
    </fieldset>
    <?php if ($isSDEHomepageEnable || $isEProHomepageEnable): ?>
        <fieldset class="fieldset info filter-summary"></fieldset>
    <?php endif; ?>
    <fieldset class="fieldset info extra-order-search" id="extra-order-search-filters">
        <?php if ($eproReorderToggleEnabled) { ?>
            <div class="action-close-div">
                <button id="filter-close-btn" aria-label="close-btn"
                class="action filter-close" type="button"><span class="action-close"></span>
                </button>
            </div>
        <?php } ?>
        <div class="upper-container-options">
            <div class="field field-order-number">
                <label class="label" for="order-number"><?=$escaper->escapeHtml(__('Order Number')); ?></label>
                <div class="control">
                    <input type="text" name="order-number" id="order-number"
                        value="<?=$escaper->escapeHtmlAttr($block->prepareInputValue('order-number')); ?>"
                        placeholder="<?=$escaper->escapeHtmlAttr(__('Enter Full or Partial Number')); ?>"
                        minlength="<?=(int)$block->getMinInputLength(); ?>" class="input-text order-filter-field"/>
                </div>
            </div>
            <?php
                $datePlaceholder = $block->getLocaleDateFormat();
                $dateAdditionalAttr = implode(' ', [
                    "placeholder='{$datePlaceholder}'",
                    "data-validate='{"
                    . "\"validate-formatted-date\": {\"dateFormat\": \"{$datePlaceholder}\"}, "
                    . "\"validate-formatted-date-range\": {\"dateFormat\":\"{$datePlaceholder}\"}"
                    . "}'"
                ]);
            ?>
            <div class="field field-dates">
                <label class="label" for="order-date-from"><?=$escaper->escapeHtml(__('Order Date')); ?></label>
                <div class="control">
                    <div class="range fields group group-2 d-flex">
                        <input type="text" name="order-date" value="<?=$datePlaceHolderValue; ?>"
                        placeholder="<?=$datePlaceHolder?>"
                         class="input-text order-filter-field" id="date-range-picker"/>
                        <img src="<?=$this->helper($helperImageClass)->getBaseUrl().
                        'wysiwyg/calender.png';?>"
                            alt="date" height="40" id="date-range-picker-icon"/>
                    </div>
                </div>
            </div>
            <div class="field field-invoice-number">
                <label class="label" for="invoice-number">
                    <?=$escaper->escapeHtml(__('Purchase Order Number')); ?>
                </label>
                <div class="control">
                    <input type="text" name="invoice-number" id="invoice-number"
                        value="<?=$escaper->escapeHtmlAttr($block->prepareInputValue('invoice-number')); ?>"
                        placeholder="<?=$escaper->escapeHtmlAttr(__('Enter Full or Partial Number')); ?>"
                        minlength="1" class="input-text order-filter-field"/>
                </div>
            </div>
            <div class="field field-order-status">
                <label class="label" for="order-status"><?=$escaper->escapeHtmlAttr(__('Order Status')); ?></label>
                <div class="control">
                    <?=$block->getOrderStatusSelectElementHtml(); ?>
                </div>

                <?php // B-1145903 - Show Order History with only shipped, ready for pickup or delivered
                if (($isSDEHomepageEnable || $isEProHomepageEnable) && !empty($orderStatus)): ?>
					<input type="hidden" id="custom-order-status" value="<?= $orderStatus; ?>"/>
                <?php endif; ?>
            </div>
            <div class="field field-order-totals order-total">
                <label class="label" for="order-total-min"><?=$escaper->escapeHtml(__('Order total')); ?></label>
                <div class="control">
                    <div class="range fields group group-2 d-flex">
                        <div class="field field-order-total">
                            <div class="control d-flex">
                                <div class="order-min-label">
                                    <span class="sub-label"><?=$escaper->escapeHtml(__('Min'));?>:</span>
                                </div>
                                <div class="min-enter-amount min-max-amt">
                                <input
                                    type="text"
                                    name="order-total-min"
                                    id="order-total-min"
                                    value="<?= $escaper->escapeHtmlAttr(
                                        $block->prepareInputIntegerValue('order-total-min')
                                    ); ?>"
                                    data-validate="{'less-than-equals-to': '#order-total-max', 'digits': true}"
                                    data-msg-less-than-equals-to="<?= $escaper->escapeHtmlAttr(__(
                                        "The 'Min' value must be lower than the 'Max' value."
                                    ))
                                            ?>"
                                    data-msg-digits="<?= $escaper->escapeHtmlAttr(__(
                                        'Please enter a valid number in this field. ' .
                                        'Enter only digits (0-9).'
                                    )) ?>"
                                    placeholder="<?= $escaper->escapeHtmlAttr(__('Enter Amt')); ?>"
                                    class="input-text order-filter-field"/>
                                </div>
                            </div>
                        </div>
                        <div class="field field-order-total order-filter-max">
                            <div class="control d-flex">
                                 <div class="order-max-label">
                                     <span class="sub-label"><?=$escaper->escapeHtml(__('Max'));?>:</span>
                            </div>
                            <div class="max-enter-amount min-max-amt">
                                <input type="text"
                                name="order-total-max"
                                id="order-total-max"
                                value="<?=$escaper->escapeHtmlAttr(
                                    $block->prepareInputIntegerValue('order-total-max')
                                ); ?>"
                                data-validate="{'digits': true}"
                                data-msg-digits="<?= $escaper->escapeHtmlAttr(__(
                                    'Please enter a valid number in this field. ' .
                                    'Enter only digits (0-9).'
                                )) ?>"
                                placeholder="<?= $escaper->escapeHtmlAttr(__('Enter Amt')); ?>"
                                class="input-text order-filter-field"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field field-action">
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="reset-btn" type="button"
                            disabled="disabled" data-role="action"
                            title="<?=$escaper->escapeHtmlAttr(__('Reset')); ?>"><span>
                            <?=$escaper->escapeHtml(__('Reset')); ?></span>
                        </button>

                        <button type="submit" class="action primary"
                         title="<?=$escaper->escapeHtmlAttr(__('Apply')); ?>">
                            <span><?=$escaper->escapeHtml(__('Apply')); ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
require([
    "jquery",
    "dateRangePicker"
], function($,dateRangePicker){
     var end = new Date();
    $('#date-range-picker').daterangepicker({
        opens: 'left',
        maxDate: end,
        autoUpdateInput: false,
        autoApply: true
    }, function(start, end, label) {

    });

    $('#date-range-picker').on('apply.daterangepicker', function(ev, picker) {
        $(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY'));
    });

    $('#date-range-picker').on('cancel.daterangepicker', function(ev, picker) {
        $(this).val('');
    });

    $('#date-range-picker-icon').on('click', function(){
        $('#date-range-picker').trigger('click');
    });

    $(document).ready(function() {
        setInterval(function(){
            if($('#date-range-picker').val().length !=0){
                $('.reset-btn').prop('disabled', false);
                }
            }, 1000);

        handleResetDisable();

        $('.order-filter-field').on("keyup", function () {
                handleResetDisable();
        });
        $('#order-status').on('change', function() {
            handleResetDisable();
        });
        $('.reset-btn').on('click', function() {
            finalUrl =  '<?= $historyurl; ?>';
            window.location.replace(finalUrl);
        });
        function handleResetDisable() {
            var filterValueEmpty = true;
            $('.order-filter-field').each(function() {
                if ($(this).val() != "") {
                    filterValueEmpty = false;
                }
            });

            if (!filterValueEmpty) {
                $('.reset-btn').prop('disabled', false);
            } else if ($('#order-status').val() == '') {
                $('.reset-btn').prop('disabled', true);
            }
            else {
                $('.reset-btn').prop('disabled', false);
            }
        }
    });
});
</script>
<?php if ($isSharedOrderEnhancementToggle) { ?>
    <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
    ->setTimeframeValue($timeframeOptions)
    ->setTimeframeSelectOptions($timeframeSelectOptions)
    ->setTemplate("Fedex_SharedDetails::shared-order-export-enhancement-modal.phtml")
    ->toHtml() ?>
<?php } else { ?>
    <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
    ->setTemplate("Fedex_SharedDetails::shared-order-export-modal.phtml")
    ->toHtml() ?>
<?php } ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "reorder_section": {
                    "component": "Fedex_Orderhistory/js/view/epro-reorder"
                    },
                    "export-commercial-reporting": {
                    "component": "Fedex_SharedDetails/js/export-commercial-reporting",
                    "recipientEmailAddressLimit": "<?= /* @noEscape */ $recipientEmailAddressLimit; ?>",
                    "isSharedOrderEnhancementToggleEnabled": "<?= /* @noEscape */ $isSharedOrderEnhancementToggle; ?>",
                    "timeframeDownIcon": "<?= /* @noEscape */ $timeframeDownIcon; ?>"
                    }
                }
            }
        }
    }
</script>
