<button class="scalable" type="button" id="<?= $block->getHtmlId() ?>" data-mage-init='{"ordersCleanup":{
    "url": "<?= $block->escapeUrl($block->getAjaxUrl()) ?>",
    "elementId": "<?= $block->getHtmlId() ?>",
    "successText": "<?= $block->escapeHtmlAttr(__('Successful!')) ?>",
    "failedText": "<?= $block->escapeHtmlAttr(__('failed! Try again?')) ?>",
    "fieldMapping": "<?= /* @noEscape */ $block->getFieldMapping() ?>"}, "validation": {}}'>
    <span id="<?= $block->getHtmlId() ?>_result"><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
</button>
