<script id="product-engine-error-messages-template" type="text/x-magento-template">
    <div id="price-box-error" class="message-block message-error d-flex mt-25 mb-30">
        <div class="icon d-flex d-no-shrink v-center">
            <img alt="Error icon" class="img-auto" src="<?php echo $this->getViewFileUrl('images/error-white.svg');?>">
        </div>
        <div class="message-text">
            <%- message %>
        </div>
        <div class="ml-auto">
            <button type="button" class="close-message" aria-label="Close error message">
            </button>
        </div>
    </div>
</script>
