<?php

/**
 * Copyright © FedEx, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
    let productPreviewImg;
    require(['jquery'], function($) {
        window.DeliveryIconUrl = "<?= /* @noEscape */ $block->getViewFileUrl('images/delivery.svg') ?>";
        window.StoreIconUrl = "<?= /* @noEscape */ $block->getViewFileUrl('images/purple-store.svg') ?>";
        window.InfoIconUrl = "<?= /* @noEscape */ $block->getViewFileUrl('images/gray-info.svg') ?>";
    });
</script>
