<div id="modal-content-renew" class="modal-content-renew-form-container" style="display:none;">
    <div class="modal-content-renew-form-sub-title">
    <span class="modal-content-renew-form-sub-heading">
        <?= $block->escapeHtml(__('Renew Catalog Item'));?>
    </span>
    </div>
    <div class="custom-model-refresh-icon">
        <img src="<?= $escaper->escapeUrl(
            $block->getViewFileUrl('Fedex_CatalogMvp::images/refresh.png'))?>"
                alt="refresh-icon-popup-icon">
    </div>
    <span class="renew-description">
        <?= $block->escapeHtml(__("Renewing this catalog item will extend the availability for one year."));?>
    </span>
    <div class="actions">
        <button class="action primary renew-cancel">CANCEL</button>
        <button class="action primary renew" id="renew-popup-container">RENEW</button>
    </div>
</div>