<div id="custom-model-delete-popup" class="custom-model-delete-popup-form-container" style="display:none;">
    <div class="custom-model-delete-popup-form-header">
        <div class="custom-model-delete-icon">
            <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/mvp-delete-popup-icon.png'))?>"
                    alt="mvp-delete-popup-icon">
        </div>
    </div>
    <div class="custom-model-delete-popup-form-sub-title">
    <span class="custom-model-delete-popup-form-sub-heading">
        <?= $block->escapeHtml(__('Are you sure you want to delete?'));?>
    </span>
    </div>
    <div class="actions">
        <button class="action primary cancel-btn-delete"><?= $block->escapeHtml(__('Cancel'));?></button>
        <button class="action primary delete-action"><?= $block->escapeHtml(__('Delete'));?></button>
        <button class="action primary bulk-delete-action" style="display: none;"><?= $block->escapeHtml(__('Delete'));?></button>
        <button class="action primary kebab-delete-action" style="display: none;"><?= $block->escapeHtml(__('Delete'));?></button>
    </div>
</div>