<div class="renew-success" style='display: none;'>
    <div class="renew-success-box-inner">
        <img src="<?=/* @noEscape */$block->getViewFileUrl('images/order-history/correct-circle-icon.png'); ?>"
                alt="Success Icon">
    </div>
    <div class = "container">
        <div class="renew-close-icon" tabindex="0"></div>
        <div class="renew-success-msg"></div>
    </div>
</div>