<script type="text/javascript">
    require([
        'Magento_Ui/js/lib/validation/validator',
        'Magento_Ui/js/lib/validation/utils',
        'jquery'
    ], function(validator, utils, $){
        validator.addRule(
            'fedex-validate-zero-or-greater',
                function (value) {
                    if (utils.isEmptyNoTrim(value)) {
                        return true;
                    }
                    value = utils.parseNumber(value);

                    return !isNaN(value) && value >= 0;
                },
                $.mage.__('Please enter a number 0 or greater in this field.')
        );
    });
</script>
