<?php
/**
 * Copyright © FedEx, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block Fedex\UploadToQuote\Block\QuoteDetails */
/** @var $escaper \Magento\Framework\Escaper */
/** @var Fedex\UploadToQuote\ViewModel\QuoteDetailsViewModel $quoteDetailsViewModel */

use Magento\Catalog\Model\Product\Type;

$quoteDetailsViewModel = $block->getData('quoteDetailsViewModel');
$isUploadToQuoteEnabled = $quoteDetailsViewModel->isUploadToQuoteEnabled();
$checkExpiryItems = $quoteDetailsViewModel->isAnyUploadToQuoteItemExpiredOrExpiredSoon();
$uploadToQuoteExpiringTitle   = $quoteDetailsViewModel?->getUploadToQuoteExpiringTitle();
$uploadToQuoteExpiringMessage = $quoteDetailsViewModel?->getUploadToQuoteExpiringMessage();
$uploadToQuoteExpiredTitle    = $quoteDetailsViewModel?->getUploadToQuoteExpiredTitle();
$uploadToQuoteExpiredMessage  = $quoteDetailsViewModel?->getUploadToQuoteExpiredMessage();
$isEproUploadToQuoteEnabled = $quoteDetailsViewModel->isEproUploadToQuoteEnable();
$isNewDocumentsApiImageEnable = $quoteDetailsViewModel->isNewDocumentsApiImageEnable();
$isD190723FixToggleEnable = $quoteDetailsViewModel->isD190723FixToggleEnable();
$quote = $quoteDetailsViewModel->getQuote(true);
$shouldShareQuote = $quoteDetailsViewModel->isToggleD206707Enabled() ? $quote : null;
$isBid = $quote->getIsBid();
$quoteStatus = $quoteDetailsViewModel->getQuoteStatusKeyByQuoteId($quote->getId(), $shouldShareQuote);
$quoteNote = $quoteDetailsViewModel->getMostRecentQuoteNote($quote->getId());
$date = $quoteNote['date'] ?? '';
$comment = $quoteNote['comment'] ?? '';
$createdBy = $quoteNote['created_by'] ?? '';

$templateClass = \Magento\Framework\View\Element\Template::class;
$allowQuoteNoteShow = ($quoteStatus == 'submitted_by_admin') ? true : false;
$previewData=[];

$statusData = $quoteDetailsViewModel->getStatusDataByQuoteId($quote->getId());

if (isset($statusData['quoteStatus']) && $statusData['quoteStatus']) {
    $quoteStatus = $statusData['quoteStatus'];
}

$deletedItems = $quoteDetailsViewModel->getDeletedItems();
$priceInfForRemainItem = $quoteDetailsViewModel->getTotalPriceInfForRemainingItem();

/** @var Fedex\Cart\ViewModel\ProductInfoHandler $productInfoHandler */
$productInfoHandler = $block->getData('productInfoHandler');

/** @var Fedex\UploadToQuote\ViewModel\UploadToQuoteViewModel $uploadToQuoteViewModel */
$uploadToQuoteViewModel = $block->getData('uploadToQuoteViewModal');
$nextStepContentFromStore = $uploadToQuoteViewModel->getUploadToQuoteConfigValue('quote_submit_next_steps');
$nextStepContentFromCompany = $block->getNextStepContent();
$allowNextStepContent = $block->getAllowNextStepContent();
$quoteDetailUrl = 'uploadtoquote/index/quotehistory/';
$isUploadToQuoteSubmitDateEnabled = $quoteDetailsViewModel->toggleUploadToQuoteSubmitDate();

$nextStepContent = '';
if ($allowNextStepContent) {
    if ($nextStepContentFromCompany) {
        $nextStepContent = $nextStepContentFromCompany;
    } elseif ($nextStepContentFromStore) {
        $nextStepContent = $nextStepContentFromStore;
    }
}
$isUploadQuoteEnabled = $uploadToQuoteViewModel->isUploadToQuoteEnable();
$progressBarDetails = $quoteDetailsViewModel->getPercentBasedOnStatus($quote->getId(), $shouldShareQuote);
$dateFormat = 'F j, Y';
$basePrice = 'BASE PRICE';
$quoteReqChgImg = 'images/upload-to-quote/info.png';
$quoteReqChgMsgTitle = 'You requested a change: ';
$changeRequestStatus = 'submitted_by_customer';
$isFuseBidToggleEnabled = $quoteDetailsViewModel->isFuseBidToggleEnabled();
$companyExtentionUrl = $uploadToQuoteViewModel->getCompanyExtentionUrl($quote);
?>
<?php
$changeRequestData[0] = $quoteDetailsViewModel;
$quoteItem = $block->getData('quote_item');
$expirationItemDetails = $quoteDetailsViewModel->getExpirationUploadToQuoteItem($quoteItem);
if (!in_array($quoteItem->getId(), $deletedItems)):
    $attributeSetId = $quoteItem->getProduct()->getAttributeSetId();
    $attributeSetName = $quoteDetailsViewModel->getProductAttributeName($attributeSetId);
    $decodeProductValue = $quoteDetailsViewModel->getProductValue($quoteItem, $quote->getId(), $shouldShareQuote);
    $productLineDetails = !empty($decodeProductValue['productRateTotal'][0]['productLineDetails']) ?
        $decodeProductValue['productRateTotal'][0]['productLineDetails']:[];
    $productJson = $quoteDetailsViewModel->getProductJson($quoteItem, $quote->getId(), $shouldShareQuote);
    $previewData[] = [
        'sku' => $quoteItem->getSku(),
        'productJson' =>  $productJson,
        'itemId' => $quoteItem->getId()
    ];
    $discount = $quoteItem->getDiscount();
    $hasDiscount = $discount > 0 ? true : false;
    $features = $productJson['features'] ?? [];
    $colorImageStyle = "width: 165px;";
    $previewUrl = $productJson['preview_url'] ?? '';
    $userProductName = $productJson['userProductName'] ?? '';
    $pricebale = $uploadToQuoteViewModel->isProductLineItems($productJson);
    $specialInstruction = $uploadToQuoteViewModel->isProductLineItems($productJson, true);
    $infoBuyRequestValue = json_encode($decodeProductValue);
    $isNonStandardFile = $uploadToQuoteViewModel
        ->isNonStandardFile($infoBuyRequestValue);
    $isBundle = $quoteItem->getProductType() === Type::TYPE_BUNDLE;
    if($isBundle) {
        $userProductName = $quoteItem->getName();
    }
    // has to get special instruction from key which is not decided yet. for now making it true
    if ($quoteDetailsViewModel->isU2QCustomerSIEnabled()) {
        $specialInstructionNegotiated = $uploadToQuoteViewModel->isSiItemNonEditable($productJson);
    } else {
        $specialInstructionNegotiated = true;
    }
    if ($pricebale && ($specialInstructionNegotiated || $isBid)) {
        $itemDetails[] = [
            'product_name' => $userProductName,
            'item_id' => $quoteItem->getId(),
            'quote_id' => $quote->getId(),
            'product_img' => $previewUrl,
        ];
        $changeRequestData[] = $itemDetails;
    }
    foreach ($features as $feature):
        if (
            (isset($feature->name) && $feature->name == 'Print Color')
            && ((isset($feature->name) && $feature->name == 'Print Color') &&
                isset($feature->choice->properties[0]->value) &&
                $feature->choice->properties[0]->value == 'B/W')
        ):
            $colorImageStyle = "-webkit-filter: grayscale(100%); filter: grayscale(100%);";
            break;
        endif;
    endforeach;
    ?>
    <tr id="item_row_id_<?= $block->escapeHtmlAttr($quoteItem->getId()) ?>" class="bundle-child item-info-parent-<?= $quoteItem->getParentItemId(); ?>">
        <td data-th="Item" class="product-block">
            <div class="product-img-div">
            <span class="product-image-container">
                <div class="product-img">
                    <?php if($attributeSetName == 'FXOPrintProducts'):?>
                        <?php if ($isNonStandardFile): ?>
                            <img alt="Product Preview" class="preview-product-img" src=
                            "<?=$block->escapeUrl($uploadToQuoteViewModel
                                ->getNonStandardImageUrl());?>"/>
                        <?php else: ?>
                            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif')) ?>"
                                 class="product-loader" alt="" <?= $isBundle ? 'style="display: none;"' : ''?>/>
                            <!--Showing preview image in u2q my quote page--->
                            <?php if ($isD190723FixToggleEnable):?>
                                <?php if($isBundle): ?>
                                    <img alt="Product Preview" class="preview-product-img"
                                         src="<?= $block->escapeUrl($quoteDetailsViewModel->productImageUrl($quoteItem->getProduct(), 72, 72));?>"/>
                                <?php else: ?>
                                    <img alt="Product Preview" class="preview-product-img"
                                         src="<?= $block->escapeUrl($block
                                             ->getViewFileUrl('images/upload-to-quote/empty-image.png')) ?>"
                                         data-bind
                                         ="attr:{onload: productPreviewImg.getPreviewImg(
                                    '<?= $block->escapeHtml($previewUrl); ?>'
                                    , $element,'<?= $block->escapeHtml($isNewDocumentsApiImageEnable); ?>')}" />
                                <?php endif; ?>
                            <?php else : ?>
                                <img alt="Product Preview" class="preview-product-img"
                                     src="<?= $block->escapeUrl($block
                                         ->getViewFileUrl('images/upload-to-quote/empty-image.png')) ?>"
                                     data-bind
                                     ="attr:{onload: productPreviewImg.getPreviewImg(
                                    '<?= $block->escapeHtml($previewUrl); ?>'
                                    , $element)}" />
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <img alt="Product Preview" class="preview-product-img"
                             src="<?= $block->escapeUrl($quoteDetailsViewModel->productImageUrl($quoteItem->getProduct(), 72, 72));?>"/>
                    <?php endif;?>
                </div>
            </span>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <?= $block->escapeHtml($userProductName) ?>
                    </strong>
                    <?php if ($isUploadQuoteEnabled && !$pricebale && !$quote->getSentToErp()): ?>
                        <div class="upload-to-quote-details-store-review-lable">
                            <?= $block->escapeHtml(__('Needs Store Review')) ?>
                        </div>
                    <?php endif; ?>
                    <?php
                    $dataItemId = '';
                    if ($features) :
                        $dataItemId = $quoteItem->getId();
                    endif;
                    ?>

                    <?php if($isBundle): ?>
                        <div class="detail-toggle pt-4 pb-4">
                            <a href="#" aria-expanded="true" class="chevron-down chevron-up fs-14 lh-24 ls-0-75 fedex-bold text-uppercase cl-digital-blue no-underline"
                               data-item-id="<?= $escaper->escapeHtmlAttr($quoteItem->getId()) ?>"
                               id="show-products-<?= $escaper->escapeHtmlAttr($quoteItem->getId()) ?>">
                                <?= $escaper->escapeHtml(__("HIDE PRODUCTS")) ?></a>
                        </div>
                        <script type="text/x-magento-init">
                            {
                                "*": {
                                    "Fedex_ProductBundle/js/order-bundle-children": {
                                        "parentSelector": "#show-products-<?= $escaper->escapeHtmlAttr($quoteItem->getId()); ?>",
                                        "childrenSelector": ".item-info-parent-<?= $quoteItem->getId() ?>",
                                        "childrenShowDetailSelector": ".item-info-parent-<?= $quoteItem->getId() ?>"
                                    }
                                }
                            }
                        </script>
                    <?php else: ?>
                        <a href="#" aria-expanded="false"
                           aria-controls=
                           "configurater-product-attr-<?= $block->escapeHtmlAttr($quoteItem->getId()) ?>"
                           class="show-product-detail-lable show-detail"
                           data-item-id="<?= $block->escapeHtmlAttr($dataItemId) ?>"
                           id="show-detail-<?= $block->escapeHtmlAttr($quoteItem->getId()) ?>">
                            <?= $block->escapeHtml(__('Show details')) ?>
                        </a>
                    <?php endif; ?>

                    <!-- Expiration inline message -->

                    <?php if ($expirationItemDetails['expired'] ?? null): ?>
                        <div class="quote-expiration-message-wrapper">
                            <div class="icon-container">
                        <span>
                            <img src="
                            <?= $block->escapeUrl($block->getViewFileUrl('images/expired-icon.png'))
                            ?>" alt="expired-icon" class="img-check-icon" />
                        </span>
                            </div>
                            <div class="item-inline-err-msg">
                                <p class="expiration-title">
                                    <?= $escaper->escapeHtml(__($uploadToQuoteExpiredTitle)) ?>
                                </p>
                                <p class="expiration-msg">
                                    <?= $escaper->escapeHtml(__($uploadToQuoteExpiredMessage)) ?>
                                </p>
                            </div>
                        </div>
                    <?php endif;?>
                    <?php if ($expirationItemDetails['expired_soon'] ?? null): ?>
                        <div class="quote-expiration-message-wrapper">
                            <div class="icon-container">
                                <img src="
                        <?= $block->escapeUrl($block->getViewFileUrl('images/expiring-icon.png')) ?>"
                                     alt="expiry-icon" class="img-check-icon" />
                            </div>
                            <div class="item-inline-warning-msg">
                                <p class="expiration-title">
                                    <?= $escaper->escapeHtml(__($uploadToQuoteExpiringTitle)) ?>
                                </p>
                                <p class="expiration-msg">
                                    <?= $escaper->escapeHtml(__($uploadToQuoteExpiringMessage)) ?>
                                </p>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
            </div>
            <!-- SKU detail 320px-->
            <table aria-describedby="cart-table-for-mobile"
                   id="sku-tbl" style="display:none" class="show-squ-div configurater-product-attr-<?= $block->escapeHtmlAttr($quoteItem->getId()) ?>">
                <tr class="table-row">
                    <td colspan="5" class="product-sku">
                        <div class="configurater-product-attr"
                             id="configurater-product-attr-<?= $block
                                 ->escapeHtmlAttr($quoteItem->getId()) ?>">
                            <?php if ($productLineDetails) { ?>
                                <table aria-describedby="cart-table-sku"
                                       class="cart-table cart-table-sku">
                                    <tr class="sku-cart-table-row-th table-row-top">
                                        <th scope="col" class="col item-sku">
                                            <?= $block->escapeHtml(__('SKU')) ?>
                                        </th>
                                        <th scope="col" class="col item-base-price">
                                            <?= $block->escapeHtmlAttr($basePrice) ?>
                                        </th>
                                        <th scope="col" class="col item-qty">
                                            <?= $block->escapeHtml(__('QTY')) ?>
                                        </th>
                                        <th scope="col" class="col item-discount">
                                            <?= $block->escapeHtml(__('DISCOUNT')) ?>
                                        </th>
                                        <th scope="col" class="col item-total">
                                            <?= $block->escapeHtml(__('TOTAL')) ?>
                                        </th>
                                    </tr>

                                    <?php  foreach ($productLineDetails as $lineItem):
                                        $detailDiscountPrice =
                                            str_replace(
                                                [ '(', ')' ],
                                                '',
                                                $lineItem['detailDiscountPrice']
                                            );
                                        ?>
                                        <tr class="table-row-sku">
                                            <td class="product-sku-td quote-sku-top">
                                                    <span class="quote-product-sku"
                                                          style="display:none">
                                                        <?= $block->escapeHtml(__('SKU')) ?>
                                                    </span>
                                                <span class="quote-product-sku-name">
                                                        <?= $block->
                                                        escapeHtml(__($lineItem['detailCode'])) ?>
                                                        -
                                                        <?=  /* @noEscape */
                                                        $lineItem['description'] ?>
                                                    </span>
                                            </td>
                                            <td class="product-sku-td">
                                                    <span class="quote-product-sku"
                                                          style="display:none">
                                                        <?= $block->escapeHtmlAttr($basePrice) ?>
                                                    </span>
                                                <span>
                                                        <?=  /* @noEscape */
                                                        $lineItem['detailPrice'] ?>
                                                    </span>
                                            </td>
                                            <td class="product-sku-td">
                                                    <span class="quote-product-sku"
                                                          style="display:none">
                                                        <?= $block->escapeHtml(__('QTY')) ?>
                                                    </span>
                                                <span>
                                                        <?=  /* @noEscape */
                                                        $lineItem['unitQuantity'] ?>
                                                    </span>
                                            </td>
                                            <td class="product-sku-td">
                                                    <span class="quote-product-sku"
                                                          style="display:none">
                                                        <?= $block->escapeHtml(__('DISCOUNT')) ?>
                                                    </span>
                                                <span>
                                                        <?= /* @noEscape */ $detailDiscountPrice ?>
                                                    </span>
                                            </td>
                                            <td class="product-sku-td">
                                                    <span class="quote-product-sku"
                                                          style="display:none">
                                                        <?= $block->escapeHtml(__('TOTAL')) ?>
                                                    </span>
                                                <span>
                                                        <?= /* @noEscape */
                                                        $lineItem['detailPrice'] ?>
                                                    </span>
                                            </td>
                                        </tr>
                                    <?php endforeach ?>
                                    <tr class="table-row"></tr>
                                </table>
                            <?php } ?>
                            <?php if (!$isNonStandardFile): ?>
                                <span class="additional-info">
                                        <?= $block->escapeHtml(__('Additional Detail')) ?>
                                    </span>
                                <ul role="listbox"
                                    aria-labelledby="show-detail-<?=
                                    $block->escapeHtmlAttr($quoteItem->getId()) ?>">
                                    <?php
                                    if (!empty($productJson['features'])):
                                        foreach ($productJson['features'] as $configAttribute):
                                            if (!empty($configAttribute->name)):?>
                                                <?= /* @noEscape */ "<li
                                                    class='detail-li' tabindex='0' role='option'>"
                                                .$configAttribute->name . ": "
                                                .$configAttribute->choice->name . "</li>";
                                            elseif (!empty($configAttribute['name'])):?>
                                                <?= /* @noEscape */ "<li
                                                    class='detail-li' tabindex='0' role='option'>"
                                                .$configAttribute['name'] . ": "
                                                .$configAttribute['choice']['name'] . "</li>";
                                            endif;
                                        endforeach;
                                    endif;
                                    ?>
                                </ul>
                            <?php endif;?>
                        </div>
                    </td>
                </tr>
            </table>
        </td>
        <td class="product-price">
            <span class="quote-product-price" style="display:none">
                <?= $block->escapeHtml(__('PRICE')) ?>
            </span>
            <?php
            if ($uploadToQuoteViewModel->isItemPriceable($infoBuyRequestValue, $isBid)):?>
                <?= /* @noEscape */ $quoteDetailsViewModel
                    ->convertPrice($quoteItem->getBaseRowTotal(), true) ?>
            <?php else: ?>
                <?= $block->escapeHtml($uploadToQuoteViewModel->getPriceDash()) ?>
            <?php endif; ?>
        </td>
        <td class="product-qty">
            <span class="quote-product-qty" style="display:none">
                <?= $block->escapeHtml(__('QTY')) ?>
            </span>
            <?= $block->escapeHtml($quoteItem->getQty()) ?></td>
        <td class="product-dis">
            <span class="quote-product-discount" style="display:none">
                <?= $block->escapeHtml(__('DISCOUNT')) ?>
            </span>
            <?php $discount = $hasDiscount
                ? $quoteDetailsViewModel->convertPrice("-" . $discount, true) : "-"; ?>
            <?= /* @noEscape */ $discount ?>
        </td>
        <td class="product-total">
            <span class="quote-product-subtotal" style="display:none">
                <?= $block->escapeHtml(__('SUBTOTAL')) ?>
            </span>
            <?php
            if ($uploadToQuoteViewModel->isItemPriceable($infoBuyRequestValue, $isBid)):?>
                <?php
                $row_total = str_replace(',', '', $quoteItem->getRowTotal());
                $item_discount = str_replace(',', '', (string)$quoteItem->getDiscount());
                $final_line_total
                    = floatval($row_total - ($item_discount == "" ? 0 : $item_discount));
                ?>
                <?= /* @noEscape */
                $quoteDetailsViewModel->convertPrice($final_line_total, true); ?>
            <?php else: ?>
                <?= $block->escapeHtml($uploadToQuoteViewModel->getPriceDash()) ?>
            <?php endif; ?>

        </td>
    </tr>
    <?php
    $siClass = '';
    $skuClass = '';
    if (!$productLineDetails) {
        $siClass = 'additional-info-tab';
    } else {
        if ($isUploadQuoteEnabled && $pricebale &&
            $quoteStatus == 'submitted_by_admin' &&
            $specialInstructionNegotiated) {
            $skuClass = 'sku-details-with-action-btn';
        } else {
            $skuClass = 'sku-details-without-action-btn';
        }
    }
    ?>
    <tr class="hide-squ-div configurater-product-attr-<?= $block->escapeHtmlAttr($quoteItem->getId()) ?>" style="display:none;">
        <td colspan="5" class="product-sku">
            <div class="<?= $block->escapeHtmlAttr($siClass) ?> configurater-product-attr"
                 id="configurater-product-attr-<?= $block->escapeHtmlAttr($quoteItem->getId()) ?>">
                <?php if ($productLineDetails) { ?>
                    <table aria-describedby="cart-table-sku"
                           class="<?= $block->escapeHtmlAttr($skuClass) ?>
                        cart-table cart-table-sku">
                        <tr class="sku-cart-table-row-th table-row-top">
                            <th scope="col" class="col item-sku">
                                <?= $block->escapeHtml(__('SKU')) ?>
                            </th>
                            <th scope="col" class="col item-base-price">
                                <?= $block->escapeHtmlAttr($basePrice) ?>
                            </th>
                            <th scope="col" class="col item-qty">
                                <?= $block->escapeHtml(__('QTY')) ?>
                            </th>
                            <th scope="col" class="col item-discount">
                                <?= $block->escapeHtml(__('DISCOUNT')) ?>
                            </th>
                            <th scope="col" class="col item-total">
                                <?= $block->escapeHtml(__('TOTAL')) ?>
                            </th>
                        </tr>

                        <!-- for 320BP -->
                        <?php  foreach ($productLineDetails as $lineItem):
                            $detailDiscountPrice =  str_replace([ '(', ')' ], '', $lineItem
                            ['detailDiscountPrice']); ?>
                            <tr class="table-row-sku">
                                <td class="product-sku-td quote-sku-top">
                                        <span class="quote-product-sku" style="display:none">
                                            <?= $block->escapeHtml(__('SKU')) ?>
                                        </span>
                                    <span class="quote-product-sku-name">
                                            <?= $block->escapeHtml(__($lineItem['detailCode'])) ?> -
                                            <?=  /* @noEscape */ $lineItem['description'] ?>
                                        </span>
                                </td>
                                <td class="product-sku-td">
                                        <span class="quote-product-sku" style="display:none">
                                            <?= $block->escapeHtmlAttr($basePrice) ?>
                                        </span>
                                    <span>
                                            <?=  /* @noEscape */ $lineItem['detailPrice'] ?>
                                        </span>
                                </td>
                                <td class="product-sku-td">
                                        <span class="quote-product-sku" style="display:none">
                                            <?= $block->escapeHtml(__('QTY')) ?>
                                        </span>
                                    <span>
                                            <?=  /* @noEscape */ $lineItem['unitQuantity'] ?>
                                        </span>
                                </td>
                                <td class="product-sku-td">
                                        <span class="quote-product-sku" style="display:none">
                                            <?= $block->escapeHtml(__('DISCOUNT')) ?>
                                        </span>
                                    <span>
                                            <?= /* @noEscape */ $detailDiscountPrice ?>
                                        </span>
                                </td>
                                <td class="product-sku-td">
                                        <span class="quote-product-sku" style="display:none">
                                            <?= $block->escapeHtml(__('TOTAL')) ?>
                                        </span>
                                    <span>
                                            <?= /* @noEscape */ $lineItem['detailPrice'] ?>
                                        </span>
                                </td>
                            </tr>
                        <?php endforeach ?>
                        <tr class="table-row"></tr>
                    </table>
                <?php } ?>
                <?php if (!$isNonStandardFile): ?>
                    <span class="additional-info">
                            <?= $block->escapeHtml(__('Additional Detail')) ?>
                        </span>
                    <ul role="listbox"
                        aria-labelledby="show-detail-<?=
                        $block->escapeHtmlAttr($quoteItem->getId())
                        ?>">
                        <?php
                        if (!empty($productJson['features'])):
                            foreach ($productJson['features'] as $configAttribute):
                                if (!empty($configAttribute->name)):?>
                                    <?= /* @noEscape */ "<li
                                        class='detail-li' tabindex='0' role='option'>"
                                    .$configAttribute->name . ": "
                                    .$configAttribute->choice->name . "</li>";
                                elseif (!empty($configAttribute['name'])):?>
                                    <?= /* @noEscape */ "<li
                                        class='detail-li' tabindex='0' role='option'>"
                                    .$configAttribute['name'] . ": "
                                    .$configAttribute['choice']['name'] . "</li>";
                                endif;
                            endforeach;
                        endif;
                        ?>
                    </ul>
                <?php endif;?>
            </div>
        </td>
    </tr>
<?php endif; ?>
