<?php
/**
 * B-1058846 - Print Quote Receipt
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Magento\NegotiableQuote\Block\Quote\View */?>
<?php
$orderHistoryHelper = $this->helper(\Fedex\Orderhistory\Helper\Data::class);
$eproClass = $orderHistoryHelper->isModuleEnabledForPrint() ? 'epro-print-order' : '';
/* B-1148619 Print Quote Receipt */
$eproClassEnhancement = $orderHistoryHelper->isEnhancementEnabledForPrint() ? 'epro-print-order-enhancement' : '';
?>
<div class="quote-details-items <?=/* @escapeNotVerified */$eproClass?>
<?=/* @escapeNotVerified */$eproClassEnhancement?>">
    <?=$block->getChildHtml('quote_items')?>
    <?=$block->getChildHtml('quote_info')?>
</div>
