<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\NegotiableQuote\Block\Quote\Totals
 */
?>
<?php

$orderHistoryHelper = $this->helper(\Fedex\Orderhistory\Helper\Data::class);
$isModuleEnabled = $orderHistoryHelper->isModuleEnabled();
?>
<?php foreach ($block->getTotals() as $code => $total): ?>
    <?php if ($total->getBlockName()): ?>
        <?=$block->getChildHtml($total->getBlockName(), false)?>
    <?php else: ?>
        <?php $style = ($total->getStyle() ? ' ' . $total->getStyle() : '');?>
        <tr class="<?=$block->escapeHtmlAttr($code . $style)?>">

                    <?php if ($isModuleEnabled && $total->getLabel() == "Quote Grand Total (Incl. Tax)"): ?>
                        <?php $total->setLabel("Quote Grand Total");?>
                    <?php endif;?>
            <th scope="col" <?=/* @noEscape */$block->getLabelProperties()?> scope="row" >
                <?php if ($total->getStrong()): ?>
                    <strong><?=$block->escapeHtml($total->getLabel())?></strong>
                <?php else: ?>
                    <?=$block->escapeHtml($total->getLabel())?>
                <?php endif;?>
            </th>
            <td <?=/* @noEscape */$block->getValueProperties()?>
                data-th="<?=$block->escapeHtmlAttr($total->getLabel())?>">
                <?php if ($total->getStrong()): ?>
                    <strong>
                        <?=/* @noEscape */$block->formatPrice(
    $total->getValue(),
    $total->getCurrency() ? $total->getCurrency() : $block->getQuote()->getQuoteCurrencyCode()
)?>
                    </strong>
                <?php else: ?>
                    <?=/* @noEscape */$block->formatPrice(
    $total->getValue(),
    $total->getCurrency() ?
    $total->getCurrency() : $block->getQuote()->getQuoteCurrencyCode()
)
?>
                <?php endif;?>
            </td>
        </tr>
    <?php endif;?>
<?php endforeach?>
