<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
?>

<input type="hidden" id="fedex_csp_csp_whitelist_entries_list" name="groups[csp_whitelist][fields][entries_list][value]"
       data-ui-id="text-groups-csp-whitelist-fields-entries-list-value" value="1">
<div class="design_theme_ua_regexp" id="grid<?php /* @noEscape */ echo $_htmlId; ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?php /* @noEscape */ echo $block->getElement()->getId(); ?>">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                    <th><?php /* @noEscape */ echo $column['label']; ?></th>
                <?php endforeach;?>
                <th class="col-actions" colspan="<?php /* @noEscape */ echo $_colspan; ?>">Action</th>
            </tr>
            </thead>
            <tbody id="entries-list"></tbody>
        </table>
    </div>
</div>

<style type="text/css">
    .admin__control-table .entry-edit::before {
        content: '\e610';
        font-size: 2rem;
    }
</style>
