<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
/** @var \Fedex\MarketplaceCheckout\ViewModel\Cart $marketplaceViewModel */
/** @var $escaper \Magento\Framework\Escaper */
$marketplaceViewModel =  $block->getData('marketplace_view_model');
$unavailableModel = $block->getData('product_availability_view_model');

/** @var \Fedex\ProductBundle\ViewModel\ItemRendererProvider $itemRendererProvider */
$itemRendererProvider = $block->getData('item_renderer_provider');

$productHelper =  $this->helper(Fedex\Delivery\Helper\Data::class);
$discountHelper = $this->helper(Magento\Checkout\Helper\Data::class);
$newDocumentImageHelper = $this->helper(Fedex\FXOCMConfigurator\Helper\Data::class);
$marketplaceCheckoutHelper = $this->helper(Fedex\MarketplaceCheckout\Helper\Data::class);

$productEngineUrl = '';
$viewModel = $block->getData('productEngineUrl_view_model');
$productViewModel = $block->getData('product_availability_view_model');
if ($viewModel->getProductEngineUrl()) {
    $productEngineUrl = $viewModel->getProductEngineUrl();
}
/** @var Fedex\Cart\ViewModel\ProductInfoHandler $productInfoHandler */
$productInfoHandler = $block->getData('productInfoHandler');

//New Document image toggle value
$newDocumentImageToggle =   $newDocumentImageHelper->getNewDocumentsApiImagePreviewToggle();

$onchangeUpdate = '';
if($marketplaceViewModel->isImprovingUpdateItemQtyCart()){
    $onchangeUpdate = 'onchange="'. $escaper->escapeHtmlAttr(
            'editCartItem.updateCart()').'"';
}

$_item = $block->getItem();
$hasLegacyDocument = false;
$checkLegacyDocApiOnCartToggle = (bool) $marketplaceViewModel->checkLegacyDocApiOnCartToggle();
$hasLegacyDocument = $checkLegacyDocApiOnCartToggle && (bool) $marketplaceViewModel->checkBundleLegacyDocumentInCart($_item);

$messages = $block->getMessages();

// Remove Mirakl price update message.
forEach($messages as $key => $message) {
    if(str_contains($message['text'], 'Price has changed from')) {
        unset($messages[$key]);
    }
}

$product = $_item->getProduct();

$additionalOption = $_item->getOptionByCode('info_buyRequest');
$additionalOptions = $additionalOption->getValue();
$decodeProductValue = json_decode($additionalOptions, true);
$productLinePriceable = $decodeProductValue['external_prod'][0]['priceable'] ?? '';
$product_json = $productInfoHandler->getItemExternalProd($_item);
$externalProductId = $product_json['id'] ?? '';
$preview_url = $product_json['preview_url'] ?? '';
$product_json['features'] = $product_json['features'] ?? [];
$features = $product_json['features'] ?? [];
$colorImageStyle = "width: 165px;";
foreach ($features as $feature) {
    if ($feature->name == 'Print Color' &&
        isset($feature->choice->properties[0]->value) &&
        $feature->choice->properties[0]->value == 'B/W' &&
        !$viewModel->isSdeStore()
    ) {
        $colorImageStyle = "-webkit-filter: grayscale(100%); filter: grayscale(100%);";
        break;
    }
}
$attributeSetId = $product->getAttributeSetId();
$newDocumentImage = false;
$isCustomize = $productHelper->getProductCustomAttributeValue($product->getId(), 'customizable');
$attribute_set_name = $productHelper->getProductAttributeName($attributeSetId);
$selfRegPreviewImage = $newDocumentImageHelper->isSelfRegPreviewImage();
if ($selfRegPreviewImage) {
    $siteName = $productHelper->getCompanySite();
    if ($siteName != "") { // for epro with catalogmvp off and legacy site name present
        $newDocumentImage = false;
    } elseif ($attribute_set_name == 'PrintOnDemand' || $newDocumentImageToggle) { // catalogmvp toggle and site nme blank
        $newDocumentImage = true;
    }
} else {
    if (($product->getData('pod2_0_editable') && ($isCustomize)) || $newDocumentImageToggle) {
        $newDocumentImage = true;
    }
}

$fixedQtyHandlerToggle = $newDocumentImageHelper->getFixedQtyHandlerToggle();
$catalogMvpProduct = $product->getData('pod2_0_editable') ?? false;

$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

/**
 * @var \Fedex\ExpiredItems\ViewModel\ExpiryMessages $expiredItemViewModal expired item toogle
 */
$expiredItemViewModal = $block->getData('expiredItemViewModal');
$expiredItemConfig = $expiredItemViewModal->getConfig();
$isExpired = ($expiredItemViewModal->isBundleItemExpired($_item) || $hasLegacyDocument);
$isExpiringSoon = ($expiredItemViewModal->isBundleItemExpiringSoon($_item));

/** item applicable for upload to quote */
/** @var \Fedex\UploadToQuote\ViewModel\UploadToQuoteViewModel $uploadToQuoteViewModel */
$uploadToQuoteViewModel =  $block->getData('uploadToQuoteViewModal');
$isUploadToQuoteEnable = $uploadToQuoteViewModel->isUploadToQuoteEnable();
$pricebale = $uploadToQuoteViewModel->isProductLineItems($product_json);
$isNonStandardFile = $uploadToQuoteViewModel->isNonStandardFile($additionalOptions);
$isPrintonDemandProduct = ($attribute_set_name == 'PrintOnDemand') ? true : false;
$unavailableQtyClass='';
if($productViewModel->isE441563ToggleEnabled() && !$productViewModel->checkProductAvailable($product)) {
    $unavailableQtyClass = $productViewModel->getUnavailableQtyCssClass()??'';
}
/** @var \Fedex\ProductBundle\ViewModel\BundleProductHandler $bundleProductHandler */
$bundleProductHandler = $block->getData('bundleProductHandler');
$isBundleProductsSetupCompleted = $bundleProductHandler->isBundleItemSetupCompleted($_item);
$childrenCount = $bundleProductHandler->getBundleChildrenCount($_item);
?>
<?php if (!$isBundleProductsSetupCompleted): ?>
    <?= $block->getChildHtml('bundle_instructions_warning'); ?>
<?php endif; ?>
<tr class="item-info item-info-<?= $_item->getId() ?>">
    <?php if (($attribute_set_name == 'FXOPrintProducts')) { ?>
    <td style="display:flex; padding: 10px;" data-th="<?= $escaper->escapeHtml(__('Item')) ?>" class="col item custom-print-item">
    <?php  } elseif ($isCustomize) { ?>
    <td style="display:flex; padding: 10px;" data-th="<?= $escaper->escapeHtml(__('Item')) ?>" class="col item custom-print-item">
    <?php } else { ?>
    <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>" class="col item">
        <?php  } ?>

        <?php if (($attribute_set_name == 'FXOPrintProducts') || ($isCustomize)) : ?>
            <?php if ($viewModel->isSdeStore()) : ?>
                <span class="product-image-container sde-product-image-container prev-img-loader">
                    <div>
                        <img alt="Product Preview" style="<?= $escaper->escapeHtml($colorImageStyle); ?>" class="preview-product-img" data-bind="attr:{src: window.checkoutConfig.sde_product_mask_image_url}" />
                    </div>
                </span>
            <?php else : ?>
                <span class="product-image-container prev-img-loader">
                <?php if($isNonStandardFile):?>
                    <div>
                        <img alt="Product Preview" class="preview-product-img"
                             src="<?= $escaper->escapeUrl($uploadToQuoteViewModel->getNonStandardImageUrl()) ?>"/>
                    </div>
                <?php elseif ($product->getTypeId() == \Magento\Catalog\Model\Product\Type::TYPE_BUNDLE) : ?>
                    <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                <?php else: ?>
                    <?php if(!$hasLegacyDocument) :?>
                        <div data-bind="if: productPreviewImg">
                            <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-2.gif')) ?>"
                                 alt="product-loader-img" class="product-loader" />
                            <img alt="Product Preview" style="<?= $escaper->escapeHtml($colorImageStyle); ?>" class="preview-product-img" data-bind="attr:{onload: productPreviewImg.getPreviewImg('<?= $escaper->escapeHtml($preview_url); ?>', $element,'<?php echo $newDocumentImage;?>')}" />
                        </div>
                    <?php else: ?>
                        <div>
                            <img src="#" alt="Product Image" class="product-empty-image" />
                        </div>
                    <?php endif;?>
                        <div data-bind="ifnot: productPreviewImg">
                            <img src="#" alt="Product Image" class="product-empty-image" />
                        </div>

                <?php endif;?>
                </span>
            <?php endif; ?>
        <?php else : ?>
            <?php if ($block->hasProductUrl()) : ?>
                <a title="<?= $escaper->escapeHtml($block->getProductName()) ?>" tabindex="-1" class="product-item-photo">
            <?php else : ?>
                <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) : ?>
                </a>
            <?php else : ?>
                </span>
            <?php endif; ?>
        <?php endif; ?>

        <div class="product-item-details">
                <strong tabindex="0" class="product-item-name">
                    <?= $escaper->escapeHtml($block->getProductName()) ?>
                </strong>
                <?php if ($messages) : ?>
                    <?php foreach ($messages as $message) : ?>
                        <div class="cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $escaper->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif; ?>
                <?php if (!$uploadToQuoteViewModel->isUploadToQuoteGloballyEnabled()) : ?>
                    <?php if ($attribute_set_name == 'FXOPrintProducts' && !empty($product_json['features'])) : ?>
                        <a href="#" aria-expanded="false" aria-controls="configurater-product-attr-<?=
                        $escaper->escapeHtmlAttr($_item->getId()) ?>" class="plain-link show-detail fedex-regular"
                           data-item-id="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"
                           id="show-detail-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
                            <?= $escaper->escapeHtml(__("Show Details"))?></a>
                        <div class="configurater-product-attr" id="configurater-product-attr-<?=
                        $escaper->escapeHtmlAttr($_item->getId()) ?>" style="display:none">
                            <?php if(!$isNonStandardFile):?>
                                <ul role="listbox" aria-labelledby="show-detail-<?=
                                $escaper->escapeHtmlAttr($_item->getId()) ?>">
                                    <?php if (!empty($product_json['features'])) {
                                        $opt = 1;
                                        foreach ($product_json['features'] as $configAttribute) {
                                            if (!empty($configAttribute->name)) { ?>
                                                <?= /* @noEscape */ "<li tabindex='-1' role='option'>"
                                                . $configAttribute->name . ": " . $configAttribute->choice->name . "</li>";
                                            }
                                            $opt++;
                                        }
                                    }
                                    ?>
                                </ul>
                            <?php endif; ?>
                        </div>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
                <div class="item-actions">
                    <div class="custom-toolbar-action">
                        <?= /* @noEscape */ $block->getActions($_item) ?>
                        <?php if ($childrenCount) : ?>
                            <span class="bundle-children-count fs-12 lh-16 fedex-regular">
                                <?= $escaper->escapeHtml(__('Items (%1)', $childrenCount)) ?>
                            </span>
                        <?php endif; ?>
                    </div>
                        <div class="pt-4 pb-4">
                            <a href="#" aria-expanded="<?= $isBundleProductsSetupCompleted?'false':'true';?>"
                               aria-controls="configurater-product-attr-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"
                               class="plain-link show-products fedex-regular icon-arrow"
                               data-item-id="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"
                               id="show-products-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
                                <?= $escaper->escapeHtml(__($isBundleProductsSetupCompleted ? 'Show Products' : 'Hide Products')) ?>
                            </a>
                        </div>
                </div>
        </div>
    </td>
    <?php if ($canApplyMsrp) : ?>
        <td class="col msrp" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice">
                        <?= $escaper->escapeHtml(__('See price before order confirmation.')) ?>
                    </span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= ($escaper->escapeHtmlAttr($helpLinkId)) ?>" data-mage-init='{"addToCart":{
                                        "helpLinkId": "#<?= $escaper->escapeJs($escaper->escapeHtml($helpLinkId)) ?>",
                                        "productName": "<?= $escaper->escapeJs($escaper->escapeHtml($product->getName())) ?>",
                                        "showAddToCart": false
                                        }
                                    }'>
                        <span><?= $escaper->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
        </td>
    <?php else : ?>
        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
            <?= /* @noEscape */ $discountHelper->convertPrice($_item->getBaseRowTotal(), true); ?>
        </td>
    <?php endif; ?>
    <td class="col qty text-center" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <div class="control qty product-engine-qty">
                <label for="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty">
                    <span class="label"><?= $escaper->escapeHtml(__('Qty')) ?></span>
                    <input id="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty"
                        name="cart[<?= $escaper->escapeHtmlAttr($_item->getId()) ?>][qty]"
                        data-cart-item-id="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                        value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                        type="number"
                        size="4"
                        step="any"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Quantity input')) ?>"
                        class="input-text qty disabled-qty"
                        data-validate="{required:true,'validate-greater-than-zero':true}"
                        data-role="cart-item-qty"
                        disabled="disabled"/>
                </label>
            </div>
        </div>
    </td>
    <?php
    $discount = $_item->getDiscount();
    $hasDiscount = $discount > 0 ? true : false;
    ?>
    <td class="col discount <?= $hasDiscount ? 'show-discount' : '' ?>" data-th="<?= $escaper->escapeHtml(__('Discount')) ?>">
        <?= /* @noEscape */ $hasDiscount ? $discountHelper->convertPrice("-" . $discount, true) : "-" ?>
    </td>

    <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) : ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?php
            $row_total = str_replace(',', '', $_item->getRowTotal());
            $item_discount = str_replace(',', '', (string)$_item->getDiscount());
            $final_line_total = floatval($row_total - ($item_discount == "" ? 0 : $item_discount)); ?>
            <?= /* @noEscape */ $discountHelper->convertPrice($final_line_total, true); ?>
        <?php endif; ?>
    </td>
    <script type="text/x-magento-init">
        {
            ".show-detail": {
                "Magento_Checkout/js/configurator-attribute": {}
            }
        }
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Fedex_ProductBundle/js/cart-bundle-children": {
                    "parentSelector": "#show-products-<?= $escaper->escapeHtmlAttr($_item->getId()); ?>",
                    "childrenSelector": ".item-info-parent-<?= $_item->getId() ?>",
                    "childrenShowDetailSelector": ".item-info-parent-<?= $_item->getId() ?> + .cart-show-detail",
                    "mobileChildrenTitleSelector":"#bundle-children-count-title-<?= $_item->getId() ?>",
                    "lastChildrenSeparatorSelector": "#last-children-separator-<?= $_item->getId() ?>"
                }
            }
        }
    </script>
    <script>
        require(['product'], function(product) {
            editCartItem = product;
        });

    </script>
</tr>

<?php if ($isExpiringSoon || $isExpired): ?>
    <tr>
        <td colspan="5" class="expiry-messages-container pb-24">
            <?php if ($isExpiringSoon && !$isExpired): ?>
                <div class="cart-expiryitem-inline-warning-msg-outer-most-info"
                     style="display: none;"
                     data-bind="visible: !$parent.isProductDisabled(<?= $externalProductId ?>)"
                >
                    <div class="cart-expiryitem-inline-info-warning-msg-container">
                        <div class="expiry-icon-container">
                            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/expiring-icon.png')) ?>"
                                 alt="expiry-icon" class="img-check-icon"/>
                        </div>
                        <div class="expiry-item-inline-warning-msg">
                            <p class="warning-title">
                                <?= $escaper->escapeHtml(__( $expiredItemConfig->getCartItemExpiryTitle())) ?>
                            </p>
                            <p class="warning-msg">
                                <?= $escaper->escapeHtml(__( $expiredItemConfig->getCartItemExpiryMessage())) ?>
                            </p>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <?php if ($isExpired ): ?>
                <div class="cart-expireditem-inline-err-msg-outer-most-info"
                     style="display: none;"
                     data-bind="visible: !$parent.isProductDisabled(<?= $externalProductId ?>)"
                >
                    <div class="cart-expireditem-inline-info-err-msg-container">
                        <div class="icon-container">
                                <span>
                                    <img src="
                                    <?= $block->escapeUrl($block->getViewFileUrl('images/expired-icon.png'))
                                    ?>" alt="" class="img-check-icon"/>
                                </span>
                        </div>
                        <div class="expired-item-inline-err-msg">
                            <p class="error-title">
                                <?= $escaper->escapeHtml(__($expiredItemConfig->getCartItemExpiredTitle())) ?>
                            </p>
                            <p class="error-msg">
                                <?= $escaper->escapeHtml(__( $expiredItemConfig->getCartItemExpiredMessage())) ?>
                            </p>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="cart-expireditem-inline-err-msg-outer-most-info"
                 style="display: none;"
                 data-bind="visible: $parent.isProductDisabled(<?= $externalProductId ?>)"
            >
                <div class="cart-expireditem-inline-info-err-msg-container">
                    <div class="icon-container">
                            <span>
                                <img src="
                                <?= $block->escapeUrl($block->getViewFileUrl('images/expired-icon.png'))
                                ?>" alt="" class="img-check-icon"/>
                            </span>
                    </div>
                    <div class="expired-item-inline-err-msg">
                        <p class="error-title">
                            <?= $escaper->escapeHtml(__( $expiredItemConfig->getCartItemExpiredTitle())) ?>
                        </p>
                        <p class="error-msg">
                            <?= $escaper->escapeHtml(__( $expiredItemConfig->getCartItemExpiredMessage())) ?>
                        </p>
                    </div>
                </div>
            </div>
        </td>
    </tr>
<?php endif; ?>
<?php if ($childrenCount) : ?>
    <tr id="bundle-children-count-title-<?= $_item->getId() ?>"
        class="weight-bold fs-14 lh-24 fedex-bold text-uppercase ls-0-75 <?= $isBundleProductsSetupCompleted ? 'd-none' : ''; ?>">
        <td colspan="5" class="pb-16">
            <?= $escaper->escapeHtml(__('Bundled Items (%1)', $childrenCount)) ?>
        </td>
    </tr>
<?php endif; ?>
<?php foreach ($_item->getChildren() as $child) : ?>
    <tr class="bundle-child item-info item-info-parent-<?= $_item->getId() ?> <?= $isBundleProductsSetupCompleted ? 'd-none' : ''; ?>">
        <?= $itemRendererProvider->getItemHtml($child) ?>
    </tr>
<?php endforeach; ?>
<tr id="last-children-separator-<?= $_item->getId() ?>" class="<?= $isBundleProductsSetupCompleted ? 'd-none' : ''; ?>">
    <td colspan="5" class="pb-12 pt-12"></td>
</tr>
