<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Fedex\MarketplaceCheckout\ViewModel\Cart $marketplaceViewModel */
$marketplaceViewModel = $block->getData('marketplace_view_model');
$unavailableModel = $block->getData('product_availability_view_model');

$productHelper = $this->helper(Fedex\Delivery\Helper\Data::class);
$discountHelper = $this->helper(Magento\Checkout\Helper\Data::class);
$newDocumentImageHelper = $this->helper(Fedex\FXOCMConfigurator\Helper\Data::class);
$marketplaceCheckoutHelper = $this->helper(Fedex\MarketplaceCheckout\Helper\Data::class);

$productEngineUrl = '';
$viewModel = $block->getData('productEngineUrl_view_model');
$productViewModel = $block->getData('product_availability_view_model');
if ($viewModel->getProductEngineUrl()) {
    $productEngineUrl = $viewModel->getProductEngineUrl();
}
/** @var Fedex\Cart\ViewModel\ProductInfoHandler $productInfoHandler */
$productInfoHandler = $block->getData('productInfoHandler');

//New Document image toggle value
$newDocumentImageToggle = $newDocumentImageHelper->getNewDocumentsApiImagePreviewToggle();

$onchangeUpdate = '';
if ($marketplaceViewModel->isImprovingUpdateItemQtyCart()) {
    $onchangeUpdate = 'onchange="' . $escaper->escapeHtmlAttr(
            'editCartItem.updateCart()') . '"';
}
$toggleViewModel = $block->getData('toggle_view_model');
$bundleProductsToggle = $toggleViewModel->getToggleConfigValue('tiger_bundle_products_toggle');

$_item = $block->getItem();
$hasLegacyDocument = false;
$checkLegacyDocApiOnCartToggle = (bool)$marketplaceViewModel->checkLegacyDocApiOnCartToggle();
$hasLegacyDocument = $checkLegacyDocApiOnCartToggle && (bool)$marketplaceViewModel->checkLegacyDocumentInCart($_item);

$marketplaceItemInfo = [];
$isMarketplaceProduct = false;
$canEditReorder = true;
$punchoutEnabled = true;
$minQty = null;
$maxQty = null;
if (!is_null($_item->getAdditionalData())) {
    $marketplaceItemInfo = json_decode($_item->getAdditionalData());
    if (isset($marketplaceItemInfo->isMarketplaceProduct)) {
        $isMarketplaceProduct = $marketplaceItemInfo->isMarketplaceProduct;
    }
    if (isset($marketplaceItemInfo->can_edit_reorder)) {
        $canEditReorder = $marketplaceItemInfo->can_edit_reorder;
    }
    if ($marketplaceViewModel->isMktCbbEnabled()) {
        if (isset($marketplaceItemInfo->punchout_enabled)) {
            $punchoutEnabled = $marketplaceItemInfo->punchout_enabled;
        }
        if ($_item && $_item->getProduct() && $_item->getProduct()?->getMainOffer()?->getMinOrderQuantity()) {
            $minQty = $_item?->getProduct()?->getMainOffer()?->getMinOrderQuantity();
        }
        if ($_item && $_item->getProduct() && $_item->getProduct()?->getMainOffer()?->getMaxOrderQuantity()) {
            $maxQty = $_item?->getProduct()?->getMainOffer()?->getMaxOrderQuantity();
        }
    }
}

$messages = $block->getMessages();

// Remove Mirakl price update message.
foreach ($messages as $key => $message) {
    if (str_contains($message['text'], 'Price has changed from')) {
        unset($messages[$key]);
    }
}

$product = $_item->getProduct();

$additionalOption = $_item->getOptionByCode('info_buyRequest');
$additionalOptions = $additionalOption->getValue();
$decodeProductValue = json_decode($additionalOptions, true);
$productLinePriceable = $decodeProductValue['external_prod'][0]['priceable'] ?? '';
$product_json = $productInfoHandler->getItemExternalProd($_item);
$externalProductId = $product_json['id'] ?? '';
$preview_url = $product_json['preview_url'] ?? '';
$product_json['features'] = $product_json['features'] ?? [];
$product_json['features'] = $isMarketplaceProduct && isset($marketplaceItemInfo->features) ?
    $marketplaceItemInfo->features : $product_json['features'];
$features = $product_json['features'] ?? [];
$colorImageStyle = "width: 165px;";
foreach ($features as $feature) {
    if ($feature->name == 'Print Color' &&
        isset($feature->choice->properties[0]->value) &&
        $feature->choice->properties[0]->value == 'B/W' &&
        !$viewModel->isSdeStore()
    ) {
        $colorImageStyle = "-webkit-filter: grayscale(100%); filter: grayscale(100%);";
        break;
    }
}
$attributeSetId = $product->getAttributeSetId();
$newDocumentImage = false;
$isCustomize = $productHelper->getProductCustomAttributeValue($product->getId(), 'customizable');
$attribute_set_name = $productHelper->getProductAttributeName($attributeSetId);
$selfRegPreviewImage = $newDocumentImageHelper->isSelfRegPreviewImage();
if ($selfRegPreviewImage) {
    $siteName = $productHelper->getCompanySite();
    if ($siteName != "") { // for epro with catalogmvp off and legacy site name present
        $newDocumentImage = false;
    } elseif ($attribute_set_name == 'PrintOnDemand' || $newDocumentImageToggle) { // catalogmvp toggle and site nme blank
        $newDocumentImage = true;
    }
} else {
    if (($product->getData('pod2_0_editable') && ($isCustomize)) || $newDocumentImageToggle) {
        $newDocumentImage = true;
    }
}

$fixedQtyHandlerToggle = $newDocumentImageHelper->getFixedQtyHandlerToggle();
$catalogMvpProduct = $product->getData('pod2_0_editable') ?? false;

$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

/** expired item toogle */
$expiredItemViewModal = $block->getData('expiredItemViewModal');
$expiredItemConfig = $expiredItemViewModal->getConfig();
$isExpired = (
    $expiredItemViewModal->isCustomerLoggedIn()
    && ($expiredItemViewModal->isItemExpired($_item) || $hasLegacyDocument)
);
$isExpiringSoon = (
    $expiredItemViewModal->isCustomerLoggedIn()
    && $expiredItemViewModal->isItemExpiringSoon($_item->getId())
);

/** item applicable for upload to quote */
/** @var \Fedex\UploadToQuote\ViewModel\UploadToQuoteViewModel $uploadToQuoteViewModel */
$uploadToQuoteViewModel = $block->getData('uploadToQuoteViewModal');
$isUploadToQuoteEnable = $uploadToQuoteViewModel->isUploadToQuoteEnable();
$pricebale = $uploadToQuoteViewModel->isProductLineItems($product_json);
$specialInstruction = $uploadToQuoteViewModel->isProductLineItems($product_json, true);
$isNonStandardFile = $uploadToQuoteViewModel->isNonStandardFile($additionalOptions);
$isPrintonDemandProduct = ($attribute_set_name == 'PrintOnDemand') ? true : false;
$isSiItemNonEditable = !$isMarketplaceProduct && $isUploadToQuoteEnable
    && $uploadToQuoteViewModel->isSiItemEditBtnDisable($product_json) && !$isPrintonDemandProduct;
$showDetails = (!empty($product_json['features']) || ($isUploadToQuoteEnable && $specialInstruction));
$unavailableQtyClass = '';
if ($productViewModel->isE441563ToggleEnabled() && !$productViewModel->checkProductAvailable($product)) {
    $unavailableQtyClass = $productViewModel->getUnavailableQtyCssClass() ?? '';
}

/** @var \Fedex\ProductBundle\ViewModel\BundleProductHandler $bundleProductHandler */
$bundleProductHandler = $block->getData('bundleProductHandler');
$isBundleParentSetupCompleted = $bundleProductHandler->isBundleParentSetupCompleted($_item);
$isSetupCompleted = $bundleProductHandler->isBundleChildSetupCompleted($_item);
$siteName = $bundleProductHandler->getCompanySite();
if ($siteName) {
    $tazToken = $bundleProductHandler->getTazToken($siteName ? false : true);
} else {
    $tazToken = null;
}
?>

<td data-th="<?= $escaper->escapeHtml(__('Item')) ?>"
    class="col item custom-print-item">
    <span class="product-image-container prev-img-loader">
        <?php if (!$isSetupCompleted): ?>
            <div onclick="editCartItem.uploadPrintBundleChildProduct(event)('<?= $product->getSku(); ?>', '<?= $siteName ?>', '<?= $tazToken; ?>', <?=(int)$_item->getId()?>)" style="cursor: pointer;">
                <img src="<?= $block->getViewFileUrl('Fedex_ProductBundle::images/bundle-upload.svg') ?>"
                     alt="Product Image" class="product-empty-image" width="80" height="80"/>
            </div>
        <?php else: ?>
            <div data-bind="if: productPreviewImg">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif')) ?>"
                     alt="product-loader-img" class="product-loader" />
                <img alt="Product Preview" style="<?= $block->escapeHtml($colorImageStyle); ?>" class="preview-product-img" data-bind="attr:{onload: productPreviewImg.getPreviewImg('<?= $block->escapeHtml($preview_url); ?>', $element,'<?php echo $newDocumentImage;?>')}" />
            </div>
        <?php endif; ?>
    </span>
    <div class="product-item-details">
        <strong tabindex="0" style="margin-left: 10px;" class="product-item-name">
            <?php if (!$isSetupCompleted): ?>
                <?= $escaper->escapeHtml($block->getProductName()) ?>
            <?php elseif (isset($product_json['userProductName'])): ?>
                <?= /* @noEscape */
                ($product_json['userProductName']); ?>
            <?php endif; ?>
        </strong>
        <?php if ($messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <div class="cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                    <div><?= $escaper->escapeHtml($message['text']) ?></div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?php if (!$uploadToQuoteViewModel->isUploadToQuoteGloballyEnabled()) : ?>
            <?php if ($attribute_set_name == 'FXOPrintProducts' && !empty($product_json['features'])) : ?>
                <a href="#" aria-expanded="false" aria-controls="configurater-product-attr-<?=
                $escaper->escapeHtmlAttr($_item->getId()) ?>" class="plain-link show-detail fedex-regular"
                   data-item-id="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"
                   id="show-detail-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
                    <?= $escaper->escapeHtml(__("Show Details")) ?></a>
                <div class="configurater-product-attr" id="configurater-product-attr-<?=
                $escaper->escapeHtmlAttr($_item->getId()) ?>" style="display:none">
                    <?php if (!$isNonStandardFile): ?>
                        <ul role="listbox" aria-labelledby="show-detail-<?=
                        $escaper->escapeHtmlAttr($_item->getId()) ?>">
                            <?php if (!empty($product_json['features'])) {
                                $opt = 1;
                                foreach ($product_json['features'] as $configAttribute) {
                                    if (!empty($configAttribute->name)) { ?>
                                        <?= /* @noEscape */
                                        "<li tabindex='-1' role='option'>"
                                        . $configAttribute->name . ": " . $configAttribute->choice->name . "</li>";
                                    }
                                    $opt++;
                                }
                            }
                            ?>
                        </ul>
                    <?php endif; ?>
                </div>
                </span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($isSetupCompleted): ?>
            <div class="item-actions">
                <div class="custom-toolbar-action <?= ($isSiItemNonEditable) ? 'si-item-non-editable' : '' ?>">
                    <?= /* @noEscape */
                    $block->getActions($_item) ?>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($isSiItemNonEditable) : ?>
            <div class="upload-to-quote-cart-edit-link">
                <a class="upload-to-quote-why-edit-button" href="#" aria-expanded="false">
                    <?= $escaper->escapeHtml(__("Why can't I edit?")) ?>
                </a>
                <div class="upload-to-quote-edit-button-msg" style="display:none">
                    <?= $uploadToQuoteViewModel->getQuoteEditButtonMsg() ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</td>
<?php if ($isSiItemNonEditable) : ?>
    <td class="mobile-why-edit-link" style="display:none">
        <a class="upload-to-quote-why-edit-button" href="#" aria-expanded="false">
            <?= $escaper->escapeHtml(__("Why can't I edit?")) ?>
        </a>
        <div class="upload-to-quote-edit-button-msg" style="display:none">
            <?= $uploadToQuoteViewModel->getQuoteEditButtonMsg() ?>
        </div>
    </td>
<?php endif; ?>
<?php if ($uploadToQuoteViewModel->isUploadToQuoteGloballyEnabled() && $isSetupCompleted): ?>
    <td class="mobile-quote-show-detail-row" style="display:none">
        <?php if ($attribute_set_name == 'FXOPrintProducts' && $showDetails) : ?>
            <a href="#" aria-expanded="false" aria-controls="configurater-product-attr-<?=
            $escaper->escapeHtmlAttr($_item->getId()) ?>"
               class="plain-link show-detail fedex-regular"
               data-item-id="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"
               id="show-detail-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
                <?= $escaper->escapeHtml(__("Show Details")) ?>
            </a>
            <div class="configurater-product-attr" id="configurater-product-attr-<?=
            $escaper->escapeHtmlAttr($_item->getId()) ?>" style="display:none;">
                <?php if (!$isNonStandardFile): ?>
                    <ul role="listbox" aria-labelledby="show-detail-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
                        <?php
                        if (!empty($product_json['features'])) {
                            $opt = 1;
                            foreach ($product_json['features'] as $configAttribute) {
                                if (!empty($configAttribute->name)) { ?>
                                    <?= /* @noEscape */
                                    "<li tabindex='-1' role='option'>"
                                    . $configAttribute->name . ": " . $configAttribute->choice->name . "</li>";
                                }
                                $opt++;
                            }
                        }
                        ?>
                    </ul>
                <?php endif; ?>
                <?php if ($isUploadToQuoteEnable && $specialInstruction) : ?>
                    <div class="upload-to-quote-show-print-instruction">
                        <p class="additional-print-instruction">
                            <?= $escaper->escapeHtml(__('Additional Print Instructions:')) ?>
                        </p>
                        <p class="print-banner">
                            <?= $escaper->escapeHtml(__($specialInstruction)) ?>
                        </p>
                    </div>
                <?php endif; ?>
            </div>
            </span>
        <?php endif; ?>
    </td>
<?php endif; ?>
<?php if ($canApplyMsrp) : ?>
    <td class="col msrp" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
        <span class="pricing msrp">
            <span class="msrp notice">
                <?= $escaper->escapeHtml(__('See price before order confirmation.')) ?>
                </span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a href="#" class="action help map" id="<?= ($escaper->escapeHtmlAttr($helpLinkId)) ?>"
                   data-mage-init='{"addToCart":{
                                    "helpLinkId": "#<?= $escaper->escapeJs($escaper->escapeHtml($helpLinkId)) ?>",
                                    "productName": "<?= $escaper->escapeJs($escaper->escapeHtml($product->getName())) ?>",
                                    "showAddToCart": false
                                    }
                                }'>
                    <span><?= $escaper->escapeHtml(__("What's this?")) ?></span>
                </a>
            </span>
    </td>
<?php else : ?>
    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
        <?= /* @noEscape */
        $discountHelper->convertPrice($_item->getBaseRowTotal(), true); ?>
    </td>
<?php endif; ?>
<td class="col qty text-center" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
    <div class="field qty">
        <div class="control qty product-engine-qty">
            <label for="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty">
                <span class="label"><?= $escaper->escapeHtml(__('Qty')) ?></span>
                <?php
                $optionHtml = '';
                $optionSelected = '';

                ?>

                <?php if ($isMarketplaceProduct && $punchoutEnabled) : ?>
                    <div class="blocked-qty">
                            <span class="qty-marketplace">
                                <?= $escaper->escapeHtmlAttr($marketplaceItemInfo->quantity) ?>
                            </span>
                        <i class="qty-tooltip"></i>
                        <div class="marketplace-tooltip fedex-light fs-16 lh-24 cl-stonegray weight-300">
                                <span>
                                    <?= $escaper->escapeHtml($marketplaceItemInfo->cart_quantity_tooltip) ?>
                                </span>
                        </div>
                    </div>
                <?php endif; ?>

                <?php
                if ((!$isMarketplaceProduct && $attribute_set_name == 'FXOPrintProducts') || ($isCustomize)) {

                    if (isset($product_json['fxo_product'])) {
                        $quantityList = json_decode($product_json['fxo_product'], true);
                        $quantityList = $quantityList['fxoProductInstance']['quantityChoices'];
                    } else {
                        $quantityList = $productInfoHandler->getQuantityChoices($_item);
                    }
                    foreach ($quantityList as $key => $quantity) {

                        if ($quantity == $escaper->escapeHtmlAttr($block->getQty())) {
                            $optionHtml .= '<option value="' . $quantity . '"' . $optionSelected . ' selected>' . $quantity . '</option>';
                        } else {
                            $optionHtml .= '<option value="' . $quantity . '"' . $optionSelected . '>' . $quantity . '</option>';
                        }
                    }
                }
                if ($catalogMvpProduct && $fixedQtyHandlerToggle) {
                    foreach (($product_json['quantityChoices'] ?? []) as $qty) {
                        if ($qty == $escaper->escapeHtmlAttr($block->getQty())) {
                            $optionHtml .= '<option value="' . $qty . '"' . $optionSelected . ' selected>' . $qty . '</option>';
                        } else {
                            $optionHtml .= '<option value="' . $qty . '"' . $optionSelected . '>' . $qty . '</option>';
                        }
                    }
                }
                ?>

                <?php if ($optionHtml) : ?>
                    <select <?= /* @noEscape */
                    $onchangeUpdate ?>
                        aria-label="Quantity"
                        id="cart-<?= /* @noEscape */
                        $_item->getId() ?>-qty"
                        name="cart[<?= /* @noEscape */
                        $_item->getId() ?>][qty]"
                        data-cart-item-id="<?= /* @noEscape */
                        $_item->getSku() ?>"
                        class="input-text qty product-engine-qty <?= $unavailableQtyClass ?>"
                        <?= !empty($unavailableQtyClass) ? 'disabled' : '' ?>
                        data-role="cart-item-qty"><?= /* @noEscape */
                        $optionHtml ?>
                    </select>
                <?php else : ?>
                    <input <?= /* @noEscape */
                    $onchangeUpdate ?>
                        id="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty"
                        name="cart[<?= $escaper->escapeHtmlAttr($_item->getId()) ?>][qty]"
                        data-cart-item-id="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                        value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                        type="number"
                        size="4"
                        step="any"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Quantity input')) ?>"
                        class="input-text qty <?= ($isSiItemNonEditable) ? 'si-item-non-editable' : '' ?> <?= $unavailableQtyClass ?>"
                        <?= !empty($unavailableQtyClass) ? 'disabled' : '' ?>
                        data-validate="{required:true,'validate-greater-than-zero':true}"
                        data-role="cart-item-qty"/>
                <?php endif; ?>
            </label>
        </div>
    </div>
</td>
<?php
$discount = $_item->getDiscount();
$hasDiscount = $discount > 0 ? true : false;
?>
<td class="col discount <?= $hasDiscount ? 'show-discount' : '' ?>"
    data-th="<?= $escaper->escapeHtml(__('Discount')) ?>">
    <?= /* @noEscape */
    $hasDiscount ? $discountHelper->convertPrice("-" . $discount, true) : "-" ?>
</td>

<td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
    <?php if ($canApplyMsrp) : ?>
        <span class="cart msrp subtotal">--</span>
    <?php else: ?>
        <?php
        $row_total = str_replace(',', '', $_item->getRowTotal());
        $item_discount = str_replace(',', '', (string)$_item->getDiscount());
        $final_line_total = floatval($row_total - ($item_discount == "" ? 0 : $item_discount)); ?>
        <?= /* @noEscape */
        $discountHelper->convertPrice($final_line_total, true); ?>
    <?php endif; ?>
</td>
<?php if ($uploadToQuoteViewModel->isUploadToQuoteGloballyEnabled() && $isSetupCompleted ): ?>
    <tr class="cart-show-detail <?= $isBundleParentSetupCompleted ? 'd-none' : '' ?>">
        <td colspan="5">
            <?php if (($attribute_set_name == 'FXOPrintProducts' || $attribute_set_name == 'FXONonCustomizableProducts') && $showDetails) : ?>
                <a href="#" aria-expanded="false" aria-controls="configurater-product-attr-<?=
                $escaper->escapeHtmlAttr($_item->getId()) ?>" class="plain-link show-detail fedex-regular"
                   data-item-id="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"
                   id="show-detail-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
                    <?= $escaper->escapeHtml(__("Show Details")) ?></a>
                <div class="configurater-product-attr" id="configurater-product-attr-<?=
                $escaper->escapeHtmlAttr($_item->getId()) ?>" style="display:none">
                    <?php if (!$isNonStandardFile): ?>
                        <ul role="listbox"
                            aria-labelledby="show-detail-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
                            <?php if (!empty($product_json['features'])) {
                                $opt = 1;
                                foreach ($product_json['features'] as $configAttribute) {
                                    if (!empty($configAttribute->name)) { ?>
                                        <?= /* @noEscape */
                                        "<li tabindex='-1' role='option'>"
                                        . $configAttribute->name . ": " . $configAttribute->choice->name . "</li>";
                                    }
                                    $opt++;
                                }
                            }
                            ?>
                        </ul>
                    <?php endif; ?>
                    <?php if ($isUploadToQuoteEnable && $specialInstruction) : ?>
                        <div class="upload-to-quote-show-print-instruction">
                            <p class="additional-print-instruction">
                                <?= $escaper->escapeHtml(__('Additional Print Instructions:')) ?>
                            </p>
                            <p class="print-banner">
                                <?= $escaper->escapeHtml(__($specialInstruction)) ?>
                            </p>
                        </div>
                    <?php endif; ?>
                </div>
                </span>
            <?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        ".show-detail": {
            "Magento_Checkout/js/configurator-attribute": {}
        }
    }
</script>
<script>
    require(['jquery','product','productEngineAttributes'], function ($,product,peAttributes) {
        editCartItem = product;
        editCartItem.setBundleProductJson(<?= (int)$_item->getId() ?>, <?= /* @noEscape */ json_encode($product_json) ?>);
    });
</script>
