<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][category_columns][{{columnsCount}}][{{typetext}}]" value="{{position}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][category_columns][{{columnsCount}}][{{enabletext}}]" value="{{enable}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][category_columns][{{columnsCount}}][{{valuetext}}]" value="{{value}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][category_columns][{{columnsCount}}][{{showtitle}}]" value="{{showTitleValue}}">