<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\AbstractOrder
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Shipping\Helper\Data $shippingHelper */
$shippingHelper = $block->getData('shippingHelper');
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()):
    return '';
endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= $block->escapeHtml(__('Shipping &amp; Handling Information')) ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php $trackCollection = $order->getTracksCollection(); ?>
        <?php  if ($trackCollection->count()): ?>
            <p>
                <a href="#" id="linkId" title="<?= $block->escapeHtmlAttr(__('Track Order')) ?>">
                    <?= $block->escapeHtml(__('Track Order')) ?>
                </a>
                <?php foreach ($trackCollection as $trackData) { ?>
                    
                    <p style="margin-bottom: 0px;"><strong>Title:</strong> <?= $trackData->getData('title')?></p>
                    <p style="margin-bottom: 0px;">
                    <strong>Carrier Code:</strong>
                        <?= $trackData->getData('carrier_code')?>
                    </p>
                    <p style="margin-bottom: 0px;">
                    <strong>Track Number:</strong>
                    <?= $trackData->getData('track_number')?>
                    </p>
                    <br/>
                <?php } ?>
            </p>
            <?= /* @noEscape */
            $secureRenderer->renderEventListenerAsTag(
                'onclick',
                "popWin('" . $block->escapeJs($shippingHelper->getTrackingPopupUrlBySalesModel($order)) .
                "','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')",
                'a#linkId'
            ) ?>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <strong><?= $block->escapeHtml($order->getShippingDescription()) ?></strong>

            <?php if ($taxHelper->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?= /** @noEscape */ $_excl ?>
            <?php if ($taxHelper->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?= $block->escapeHtml(__('Incl. Tax')) ?> <?= /** @noEscape */ $_incl ?>)
            <?php endif; ?>
        <?php else: ?>
            <?= $block->escapeHtml(__('No shipping information available')) ?>
        <?php endif; ?>
    </div>
</div>
<?php  $transactionId = $order->getPayment()->getRetailTransactionId();
if(!is_null($transactionId)):?>
    <div class="transaction-details-container" style="float: left;margin:2px 0px 0px 58px;">
        <div class="retails-payment-details">
            <strong><?= $block->escapeHtml(__('Retail Transaction Id: ')) ?></strong>
            <span><?= $transactionId;?></span>
        </div>
    </div>
<?php endif; ?>
