<?php
?>
<input type="hidden" id="popup-url" value="<?php echo $block->getUrl('customergroup/options/assigngroup'); ?>"/>
<input type="hidden" id="save-url" value="<?php echo $block->getUrl('customergroup/options/save'); ?>"/>
<div id="custom-model-popup" class="custom-model-popup" style="width:500px;height:500px;display:none;">
<select class="select2" id="asign_group" style="width:400px">
    <option value="">Select Customer Group...</option>
</select>
</div>