<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$productHelper =  $this->helper(Fedex\Delivery\Helper\Data::class);
$discountHelper = $this->helper(Magento\Checkout\Helper\Data::class);

$productEngineUrl = '';
$viewModel = $block->getData('productEngineUrl_view_model');
$productViewModel = $block->getData('product_availability_view_model');
if ($viewModel->getProductEngineUrl()) {
    $productEngineUrl = $viewModel->getProductEngineUrl();
}
/** @var Fedex\Cart\ViewModel\ProductInfoHandler $productInfoHandler */
$productInfoHandler = $block->getData('productInfoHandler');

$_item = $block->getItem();
$product = $_item->getProduct();

$additionalOption = $_item->getOptionByCode('info_buyRequest');
$additionalOptions = $additionalOption->getValue();
$product_json = $productInfoHandler->getItemExternalProd($_item);
$features = $product_json['features'] ?? [];
$colorImageStyle = "width: 165px;";
foreach ($features as $feature) {
    if (
        $feature->name == 'Print Color' &&
        isset($feature->choice->properties[0]->value) &&
        $feature->choice->properties[0]->value == 'B/W' &&
        !$viewModel->isSdeStore()
    ) {
        $colorImageStyle = "-webkit-filter: grayscale(100%); filter: grayscale(100%);";
        break;
    }
}
$attributeSetId = $product->getAttributeSetId();
$isCustomize = $productHelper->getProductCustomAttributeValue($product->getId(), 'customizable');
$attribute_set_name = $productHelper->getProductAttributeName($attributeSetId);

$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

/** expired item toogle */
$expiredItemViewModal = $block->getData('expiredItemViewModal');
$expiredItemConfig = $expiredItemViewModal->getConfig();
$isExpired = ($expiredItemViewModal->isCustomerLoggedIn() &&
            $expiredItemViewModal->isItemExpired($_item)) ? true : false;
$isExpiringSoon = ($expiredItemViewModal->isCustomerLoggedIn() &&
            $expiredItemViewModal->isItemExpiringSoon($_item->getId())) ? true : false;

$unavailableQtyClass='';
if($productViewModel->isE441563ToggleEnabled() && !$productViewModel->checkProductAvailable($product)) {
    $unavailableQtyClass = $productViewModel->getUnavailableQtyCssClass()??'';
}

?>
<tbody class="cart item">
    <?php if ($isExpiringSoon && !$isExpired): ?>
        <tr>
            <td colspan="5">
                <div class="mobile-expiry-soon-msg-container">
                    <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/expiring-icon.png')) ?>"
                    alt="expiry-icon" class="mobile-img-check-icon" />
                    <div class="mobile-expiring-msg">
                        <?= $escaper->escapeHtml(__($expiredItemConfig->getCartItemExpiryTitle())) ?>
                    </div>
                </div>
            </td>
        </tr>
    <?php endif; ?>
    <?php if ($isExpired && !$productViewModel->checkCartHaveUnavailbleProduct()): ?>
        <tr>
            <td colspan="5">
            <div class="mobile-expireditem-msg-container">
                <div class="icon-container">
                    <span >
                        <img src="
                        <?= $block->escapeUrl($block->getViewFileUrl('images/expired-icon.png'))
                        ?>" alt="" class="img-check-icon" />
                    </span>
                </div>
                    <div class="mobile-expired-item-inline-err-msg">
                        <p class="mobile-expired-error-title">
                            <?= $escaper->escapeHtml(__($expiredItemConfig->getCartItemExpiredTitle()))
                            ?>
                        </p>
                        <p class="mobile-expired-error-msg">
                            <?= $escaper->escapeHtml(__($expiredItemConfig->getCartItemExpiredMessage())
                            ) ?>
                        </p>
                    </div>
                </div>
            </td>
        </tr>
    <?php endif; ?>
    <tr class="item-info">

    <?php if (($attribute_set_name == 'FXOPrintProducts')) { ?>
        <td style="display:flex; padding: 10px;" data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item custom-print-item">
    <?php  } elseif ($isCustomize) {?>
        <td style="display:flex; padding: 10px;" data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item custom-print-item">
    <?php } else { ?>
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
        <?php  }?>

        <?php if (($attribute_set_name == 'FXOPrintProducts') || ($isCustomize)):?>
                <?php if ($viewModel->isSdeStore()): ?>
                    <span class="product-image-container sde-product-image-container prev-img-loader" >
                        <div>
                            <img alt="Product Preview" style="<?= $block->escapeHtml($colorImageStyle); ?>" class="preview-product-img" data-bind="attr:{src: window.checkoutConfig.sde_product_mask_image_url}" />
                        </div>
                    </span>
                <?php else : ?>
                    <span class="product-image-container prev-img-loader" >
                        <div data-bind="if: productPreviewImg">
                            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif')) ?>" class="product-loader" />
                            <img alt="Product Preview" style="<?= $block->escapeHtml($colorImageStyle); ?>" class="preview-product-img" data-bind="attr:{onload: productPreviewImg.getPreviewImg('<?= $block->escapeHtml($product_json['preview_url']); ?>', $element)}" />
                        </div>
                        <div data-bind="ifnot: productPreviewImg">
                            <img src="#" alt="Product Image" class="product-empty-image" />
                        </div>
                    </span>
                <?php endif; ?>
            <?php else:?>
                <?php if ($block->hasProductUrl()):?>
                    <a title="<?= $block->escapeHtml($block->getProductName()) ?>"
                        tabindex="-1"
                        class="product-item-photo">
                <?php else:?>
                    <span class="product-item-photo">
                <?php endif;?>
                    <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                <?php if ($block->hasProductUrl()):?>
                    </a>
                <?php else:?>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
            <!-- Resolve ADA Issue on Cart Summary Page for Multi Products -->
            <div class="product-item-details">
                <?php if ($attribute_set_name == 'FXOPrintProducts' || ($isCustomize)): ?>
                    <strong tabindex="0" style="margin-left: 10px;" class="product-item-name">
                <?php else:?>
                    <strong tabindex="0" class="product-item-name">
                <?php endif; ?>
                    <?php if ($attribute_set_name == 'FXOPrintProducts') { ?>
                        <?php if (isset($product_json['userProductName'])) { ?>
                            <?= /* @noEscape */ ($product_json['userProductName']); ?>
                        <?php } ?>
                    <?php } elseif ($isCustomize) { ?>
                        <?php
                            if(isset($product_json['fxo_product'])):
                                $fxoProduct = json_decode($product_json['fxo_product'] ?? "{}")->fxoProductInstance ?? []; ?>
                                <?= /* @noEscape */($fxoProduct ? $fxoProduct->name : $product->getName()); ?>
                        <?php else: ?>
                                <?= /* @noEscape */($product_json['userProductName'] ?? $product->getName()); ?>
                        <?php endif; ?>
                    <?php  } else {  ?>
                        <?php if ($block->hasProductUrl()):?>
                            <?= $block->escapeHtml($block->getProductName()) ?>
                        <?php else:?>
                            <?= $block->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    <?php  }  ?>
                </strong>
                <?php if ($_options = $block->getOptionList()):?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option):?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])):?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else:?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()):?>
                    <?php foreach ($messages as $message):?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock):?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>

                <?php if ($attribute_set_name == 'FXOPrintProducts'): ?>
                    <a href="#" aria-expanded="false" aria-controls="configurater-product-attr-<?= $block->escapeHtmlAttr($_item->getId()) ?>" class="plain-link show-detail" data-item-id="<?= $block->escapeHtmlAttr($_item->getId()) ?>" id="show-detail-<?= $block->escapeHtmlAttr($_item->getId()) ?>">Show details</a>
                    <div class="configurater-product-attr" id="configurater-product-attr-<?= $block->escapeHtmlAttr($_item->getId()) ?>" style="display:none;">
                            <ul role="listbox" aria-labelledby="show-detail-<?= $block->escapeHtmlAttr($_item->getId()) ?>">
                                <?php
                                if (!empty($product_json['features'])) {
                                    $opt = 1;
                                    foreach ($product_json['features'] as $configAttribute) {
                                        if (!empty($configAttribute->name)) {?>
                                            <?= /* @noEscape */"<li tabindex='0' role='option'>".$configAttribute->name.": ".$configAttribute->choice->name."</li>";
                                        }
                                        $opt++;
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </span>
                <?php endif;?>
                    <div class="custom-toolbar-action">
                    <?= /* @noEscape */ $block->getActions($_item) ?>
                    </div>
                <?php if ($isExpiringSoon && !$isExpired): ?>
                <div class="cart-expiryitem-inline-warning-msg-outer-most-info">
                        <div class="cart-expiryitem-inline-info-warning-msg-container">
                            <div class="expiry-icon-container">
                                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/expiring-icon.png')) ?>"
                                alt="expiry-icon" class="img-check-icon" />
                            </div>
                            <div class="expiry-item-inline-warning-msg">
                                <p class="warning-title">
                                    <?= $escaper->escapeHtml(__($expiredItemConfig->getCartItemExpiryTitle())) ?>
                                </p>
                            </div>
                        </div>
                    </div>
                <?php endif;?>
                <?php if ($isExpired): ?>
                    <div class="cart-expireditem-inline-err-msg-outer-most-info">
                        <div class="cart-expireditem-inline-info-err-msg-container">
                            <div class="icon-container">
                                <span >
                                    <img src="
                                    <?= $block->escapeUrl($block->getViewFileUrl('images/expired-icon.png'))
                                    ?>" alt="" class="img-check-icon" />
                                </span>
                            </div>
                            <div class="expired-item-inline-err-msg">
                                <p class="error-title">
                                    <?= $escaper->escapeHtml(__($expiredItemConfig->getCartItemExpiredTitle()))
                                    ?>
                                </p>
                                <p class="error-msg">
                                    <?= $escaper->escapeHtml(__($expiredItemConfig->getCartItemExpiredMessage())
                                    ) ?>
                                </p>
                            </div>
                        </div>
                    </div>
                <?php endif;?>
            </div>
        </td>
        <?php if ($canApplyMsrp):?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice">
                        <?= $block->escapeHtml(__('See price before order confirmation.')) ?>
                    </span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else:?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= /* @noEscape */$discountHelper->convertPrice($_item->getBaseRowTotal(), $format = true); ?>
            </td>
        <?php endif; ?>
        <td class="col qty text-center" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <div class="control qty product-engine-qty">
                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty" >
                      <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                        <?php
                            $optionHtml = '';
                            $optionSelected = '';

                        if ($attribute_set_name == 'FXOPrintProducts' || ($isCustomize)) {

                            if(isset($product_json['fxo_product'])) {
                                $quantityList = json_decode($product_json['fxo_product'], true);
                                $quantityList = $quantityList['fxoProductInstance']['quantityChoices'];
                            } else {
                                $quantityList = $productInfoHandler->getQuantityChoices($_item);
                            }
                            foreach ($quantityList as $key => $quantity) {

                                if ($quantity == $block->escapeHtmlAttr($block->getQty())) {

                                    $optionHtml .= '<option value="'.$quantity.'"'.$optionSelected.' selected>'.$quantity.'</option>';
                                } else {

                                     $optionHtml .= '<option value="'.$quantity.'"'.$optionSelected.'>'.$quantity.'</option>';
                                }
                            }
                            ?>
                            <?php if ($optionHtml): ?>
                               <select aria-label="Quantity"
                               id="cart-<?= /* @noEscape */$_item->getId()?>-qty"
                               name="cart[<?= /* @noEscape */$_item->getId()?>][qty]"
                               data-cart-item-id="<?= /* @noEscape */$_item->getSku()?>"
                               class="input-text qty product-engine-qty <?= $unavailableQtyClass?>"
                               <?= !empty($unavailableQtyClass) ? 'disabled' : '' ?>
                               data-role="cart-item-qty"
                               <?= $isExpired ? 'disabled' : '' ?> ><?= /* @noEscape */ $optionHtml?></select>
                         <?php else: ?>
                             <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                   name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                   data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                   value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                   type="number"
                                   size="4"
                                   step="any"
                                   aria-label="<?= $block->escapeHtmlAttr(__('Quantity input')) ?>"
                                   class="input-text qty <?= $unavailableQtyClass?>"
                                   <?= !empty($unavailableQtyClass) ? 'disabled' : '' ?>
                                   data-validate="{required:true,'validate-greater-than-zero':true}"
                                   data-role="cart-item-qty"
                                   <?= $isExpired ? 'disabled' : '' ?> />
                        <?php endif; ?>
                        <?php } else { ?>
                             <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                   name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                   data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                   value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                   type="number"
                                   size="4"
                                   step="any"
                                   aria-label="<?= $block->escapeHtmlAttr(__('Quantity input')) ?>"
                                   class="input-text qty <?= $unavailableQtyClass?>"
                                   <?= !empty($unavailableQtyClass) ? 'disabled' : '' ?>
                                   data-validate="{required:true,'validate-greater-than-zero':true}"
                                   data-role="cart-item-qty"
                                   <?= $isExpired ? 'disabled' : '' ?> />
                        <?php } ?>
                    </label>
                </div>
            </div>
        </td>
        <td class="discountval col qty"
                data-th="<?=$block->escapeHtml(__('Discount'))?>">
        <?php   if($_item->getDiscount()>0): ?>
        <?= /* @noEscape */ $discountHelper->convertPrice("-".$_item->getDiscount(), $format = true) ?>
        <?php   elseif($_item->getDiscount()==0): ?>
            <span class='price discoutnull'>-</span>
        <?php endif;?>
        </td>

        <td class="col subtotal" data-th="<?=$block->escapeHtml(__('Subtotal'))?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else:?>
                <?php
                    $row_total = str_replace(',', '', $_item->getRowTotal());
                    $item_discount = str_replace(',', '', (string)$_item->getDiscount()) ;
                    $final_line_total = floatval($row_total - ($item_discount == "" ? 0 : $item_discount));?>
                <?= /* @noEscape */$discountHelper->convertPrice($final_line_total, $format = true);?>
            <?php endif; ?>
        </td>
    </tr>
</tbody>
<script type="text/x-magento-init">
    {
        ".show-detail": {
            "Magento_Checkout/js/configurator-attribute": {}
        }
    }
</script>
